### ISSUE TITLE
Being able to configure the casing of the field ids

### ISSUE THREAD

**Issue by zeckdude** [prismicio/slice-machine#1009]
### Is your feature request related to a problem? Please describe.

Yes. the casing of the field id is always snake case, but I would like for it to be camel case by default. Right now I always need to change it.

### Describe the solution you'd like

A way to configure the casing for that default field id name

### Describe alternatives you've considered

None. I have to manually edit in the slice machine which sucks.

**Comment by mdeclercq** [comment]
Hi @zeckdude,

Thanks for suggesting this. 
The reason why the field ids are in snake case is because the GraphQL api to fetch Prismic content hides camelCase fields. This was enforced in Slice Machine after the issue https://github.com/prismicio/slice-machine/issues/222. 

There is no plan for the moment to change the GraphQL api to support camelCase fields so this won't be resolved soon.

**Comment by zeckdude** [comment]
> Hi @zeckdude,
> 
> 
> 
> Thanks for suggesting this. 
> 
> The reason why the field ids are in snake case is because the GraphQL api to fetch Prismic content hides camelCase fields. This was enforced in Slice Machine after the issue https://github.com/prismicio/slice-machine/issues/222. 
> 
> 
> 
> There is no plan for the moment to change the GraphQL api to support camelCase fields so this won't be resolved soon.

Thanks for your reply but I'm not sure if you're understanding what I'm asking for. As it stands now, Prismic allows me to change the ID to anything I want, including camelcase. Therefore I know the ID can be in camelcase. All I'm saying is that if my preference is to always have it in camelcase, don't make me change it manually every time but instead give me the option to have it be camelcase by default.

**Comment by zeckdude** [comment]
And honestly I'm sorry that there are complications in the background for you to figure out a solution for this but that shouldn't be my problem as a customer. Clearly you support camelcase since I can manually set it to be camelcase so just make it so by default so it's a much better user experience.

**Comment by mdeclercq** [comment]
Hi @zeckdude,

Thanks again for your feedback, and again sorry about the inconvenience. As I mentioned above, we are aware of the issue but it's not prioritised for now.
We have open an internal ticket to keep track of the topic, I am closing this issue now until the teams has plan about it.

Thanks for your understanding,

**Comment by zeckdude** [comment]
If you close the ticket how will I ever find out if you actually get around to fixing this? I have to assume this will fall by the wayside just like the countless number of unanswered requests on the Prismic forum. Very sad.
