### ISSUE TITLE
Getting error while trying to take an screenshot from simulator

### ISSUE THREAD

**Issue by amendezm** [prismicio/slice-machine#1025]
### Versions

- slice-machine-ui: v1.4.0 
- node: v18.16.0 
- OS: windows 11 22H2 version, also happens on wsl (ubuntu 22.04 distro)

### Reproduction

Getting error while trying to take an screenshot from simulator

![image](https://github.com/prismicio/slice-machine/assets/26444448/2c335b7b-b197-48cd-8eaf-60e2964e89e4)

I see this 500 error code on console:
 
![image](https://github.com/prismicio/slice-machine/assets/26444448/6f188c42-0f9b-4bec-8e65-296137bf4944)

and this message:

`A browser context has not been initialized. Run SliceMachineManager.screenshots.prototype.initBrowserContext() before re-calling this method.`

This is my `package.json`

```
{
  "name": "nextjs",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "slicemachine": "start-slicemachine"
  },
  "dependencies": {
    "@prismicio/client": "^7.1.0",
    "@prismicio/next": "^1.3.2",
    "@prismicio/react": "^2.7.1",
    "classnames": "2.3.2",
    "eslint": "8.42.0",
    "eslint-config-next": "13.4.6",
    "next": "13.4.6",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-icons": "4.10.1"
  },
  "devDependencies": {
    "@slicemachine/adapter-next": "^0.3.1",
    "@types/node": "20.3.1",
    "@types/react": "18.2.14",
    "autoprefixer": "10.4.14",
    "eslint": "8.33.0",
    "eslint-config-next": "13.1.6",
    "eslint-config-prettier": "8.6.0",
    "eslint-plugin-prettier": "4.2.1",
    "eslint-plugin-react": "7.32.2",
    "eslint-plugin-react-hooks": "4.6.0",
    "postcss": "8.4.24",
    "slice-machine-ui": "^1.4.0",
    "tailwindcss": "3.3.2"
  }
}

```

I would really appreciate your help

Thank you

**Comment by xrutayisire** [comment]
Thanks for the report, @amendezm 

We saw that you're not alone and others had the same problem. We will investigate why and come with a plan, it's not the first time this feature is flakky and we may change the way we are doing for this need in the future.

**Comment by amendezm** [comment]
Thanks 🙏🏼

**Comment by renardsas** [comment]
Same error with slice machine ui v1.5.0 and nuxt 3 v 3.6.2
### Versions

- slice-machine-ui: v1.5.0
- node: v18.16.0
- OS: windows 11

The latest version of Slice Machine is truly excellent, and the new builder is great as well. Congratulations on all the improvements made since the beginning of Slice Machine.

**Comment by mdeclercq** [comment]
Hi,

The Slice Machine screenshot feature has been deprecated and removed. 
Instead, we improved the capabilities of custom screenshots (handling copy paste), more information in the release [1.8.0](https://github.com/prismicio/slice-machine/releases/tag/slice-machine-ui%401.8.0)

I am closing the issue.

Thanks,
