### ISSUE TITLE
Error in `@slicemachine/adapter-next` during `slice:update` hook: Cannot read properties of undefined (reading 'parsers') 

### ISSUE THREAD

**Issue by eraykeskinmac** [prismicio/slice-machine#1043]
### Versions

- slice-machine-ui: 1.5.0
- node: v20.4.1

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

**Comment by mdeclercq** [comment]
Hi @eraykeskinmac,

Thanks for reporting, but we don't have sufficient information to reproduce the issue.
Could you provide additional information, like a scenario or a minimal project to reproduce the issue?

Thanks,

**Comment by mdeclercq** [comment]
Hi again, 

I just checked with the team, this should be fixed in slice-machine-ui `1.5.1` 🎉

Please re-open or comment the issue if this happens again.

**Comment by xrutayisire** [comment]
To complete Mathieu answer, you also need to update the adapter to version « @slicemachine/adapter-next@0.3.4» 😉
