### ISSUE TITLE
Unable to Push Slices and Custom Type: 400

### ISSUE THREAD

**Issue by priyaprafful** [prismicio/slice-machine#1077]
### Versions

- slice-machine-ui:"^1.5.2"
- node:18.17.0

### Reproduction

The user is trying to push several custom types and slices changes to prismic using the slice machine. However, every time we click on the "Push to Prismic" button they get the following error on the console:

<img width="707" alt="image" src="https://github.com/prismicio/slice-machine/assets/43381242/a2c988d4-ec1b-41cb-8448-1353cc85313d">

https://community.prismic.io/t/unable-to-upload-screenshot-with-status-code-400/13711

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
I won't be able to reproduce the issue on my local.

**Comment by comeprismic** [comment]
Hi! We managed to reproduce the issue and are investigating at the moment to release a fix over the next cycles.

**Comment by comeprismic** [comment]
We released a fix on [v1.19.0](https://github.com/prismicio/slice-machine/releases) that should solve the issue in most of the cases. Some issues can still happen with a really low internet connection. I'm closing the issue now, feel free to reopen it whenever it happens again.
