### ISSUE TITLE
Avoid Layout shift from the main layout grid scrollbar

### ISSUE THREAD

**Issue by cbommart** [prismicio/slice-machine#1097]
Just a minor request to add the CSS `scrollbar-gutter: stable;` property on the main layout grid to avoid a layout shift when you go from pages with a scrollbar to scrollbarless pages. This is really visible since the 1.8.0 version.

**Comment by mdeclercq** [comment]
Hi @cbommart,

Thank you for the feedback.  Are you talking about this kind of layout shift?

https://github.com/prismicio/slice-machine/assets/6433957/91b88ef7-bf35-4880-9046-5c2788a447e4

If not, could you tell us more (ideally with a screen recording) and let us know which browser you are using?

Thanks!

**Comment by cbommart** [comment]
Hello ! yes, this is this layout shit I am talking about. Sorry for not giving you screen share directly.

**Comment by bapmrl** [comment]
Hello @cbommart,

This specific layout shift will be resolved in next release, however, you might still experience layout shifts when using the Custom Type Builder or the Slice Builder. Sadly, setting the `scrollbar-gutter` property to `stable` doesn't work with macOS's overlay scrollbar. Note that we will incrementally redesign these pages in the future and that will fix layout shifts for good.

Thank you and don't hesitate if you notice any other issue,
