### ISSUE TITLE
Sass-loader error Angular v16

### ISSUE THREAD

**Issue by ivanRS08** [prismicio/slice-machine#1099]
Se realizo una migracion a Angular16.

Pero al correr el proyecto me marca N errores.

 Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

(max-width: 991px) isn't a valid CSS value.
   ╷
13 │   @media #{$max991} {
   │            ^^^^^^^

Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
expected selector.
   ╷
19 │       color: #fff;

**Comment by mdeclercq** [comment]
Hi,

I don't see how this error is related to SliceMachine. The message indicates something between Angular and sass-loader.

I'll close the issue, but we can re-open it if you provide us more context with a way to reproduce the issue and it is actually related to SliceMachine.

Thanks,
