### ISSUE TITLE
Richtext field mock and the richtext field response from prismic doesn't match.

### ISSUE THREAD

**Issue by thilinaaligent** [prismicio/slice-machine#1108]
### Versions

- slice-machine-ui: v1.8.0
- node: v16

### Reproduction

Richtext field mock and the richtext field response from prismic doesn't seem to match. Are these suppose to be in same format? 

mock: 
```
[
	{
		"__TYPE__": "SharedSliceContent",
		"variation": "default",
		"primary": {
			"test_content": {
				"__TYPE__": "StructuredTextContent",
				"value": [
					{
						"type": "paragraph",
						"content": {
							"text": "Elit sunt non ut id sunt consectetur Lorem sit officia nostrud voluptate amet."
						}
					}
				]
			}
		},
		"items": []
	}
]
```
response from prismic:
```
[
    {
        "variation": "default",
        "version": "initial",
        "items": [
            {}
        ],
        "primary": {
            "test_content": [
                {
                    "type": "paragraph",
                    "text": "lorem ipsum",
                    "spans": []
                }
            ]
        },
        "id": "test$09574c82-eb49-47f8-9643-1a56e0c0fc61",
        "slice_type": "test",
        "slice_label": null
    }
]
```
### Steps to reproduce
create a non repeatable richtext field in a slice, compare the generated mock vs the document response from prismic

### What is expected?
Both to be equal 

### What is actually happening?
They are different

**Comment by mdeclercq** [comment]
Hi @thilinaaligent,
 
Good question, it's actually expected that both formats are different. 
When the mock data are used when simulating a Slice in Slice Simulator, they are transformed to the api format.

I'll close this as it works as expected. Feel free to comment in case you have any questions.

Thanks,
