### ISSUE TITLE
`Boolean` field with `default to true` returns `null`

### ISSUE THREAD

**Issue by KartikWatts** [prismicio/slice-machine#1181]
### Versions

- slice-machine-ui: 1.18.0 
- node: 19.3.0 

### Reproduction

I'm attaching the test-link to check the flow:
https://prismic-test-tau.vercel.app/test

Also attaching the loom video for instructions:
https://www.loom.com/share/7985b0c8f43744eb90cacadbd765d440

<details open>
<summary>Additional Details</summary>
<br>
Attaching the github repository for code implementation: [https://github.com/KartikWatts/prismic-test](https://github.com/KartikWatts/prismic-test)

</details>

### Steps to reproduce
1. Choose a Custom Type and click the `Add a new field` button.
2. Choose field type as `Boolean`:
![Screenshot_547](https://github.com/prismicio/slice-machine/assets/22623256/3ba87ce1-2aef-4afe-a25e-504865cf9092)
3. Edit the field to check `Default to true` and upload the model to Prismic:
![Screenshot_549](https://github.com/prismicio/slice-machine/assets/22623256/77312ed1-d4b6-48a4-a51e-3c3e957f7ed1)
4. Assert the Prismic actually shows the toggle field as `true` for each Document:
![Screenshot_552](https://github.com/prismicio/slice-machine/assets/22623256/72f95ac8-8b30-4499-9491-609a2315229c)

### What is expected?
All Document page slices using that Custom type should have the field value reflected as `true` and returned when called from the client.
The test link should display the JSON data for every doc as:
```{"test":true,"test2":true,"test3":true,"testflag":true}```

### What is actually happening?
Only the Documents that are newly published after the Custom type update return the field value as `true`, by default every Document returns the field value as `null`.
The test link displays the JSON data for untouched docs as:
```{"test":true,"test2":true,"test3":true,"testflag":null}```

**Please go through the loom video for demonstration. If the bug is verified, and possible, kindly assign the issue to me, I would love to work on it and resolve it at the earliest.**

**Comment by comeprismic** [comment]
Hello @KartikWatts , thanks for submitting the issue. We are aware of it and managed to reproduce it. 
We track it internally and we'll get back to you when it's fixed. For now I'll close the issue.
