### ISSUE TITLE
Got '@slicemachine/adapter-universal@latest' is not in this registry when running init script

### ISSUE THREAD

**Issue by ZYSzys** [prismicio/slice-machine#1199]
### Versions

- slice-machine-ui: 
- node: v16.20.1

### Reproduction
I want to start from scratch, after running `npx @slicemachine/init`, I got npm 404 error.
It looks like the `init` script was going to download the `@slicemachine/adapter-universal`, but it isn't existed on npm registry. See: https://www.npmjs.com/search?q=%40slicemachine%2Fadapter-universal

![image](https://github.com/prismicio/slice-machine/assets/23313266/9cc925a1-f02d-4a6c-a609-c9056f4fdf3e)

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
`npx create-next-app@latest`

`npx @slicemachine/init`

### What is expected?
The `init` script could be executed successfully.

### What is actually happening?
npm 404 error.

**Comment by ZYSzys** [comment]
OK, I got it, this is because I'm using `next@v14`, maybe we could make some change to be compatible with the latest Next.js version.

**Comment by xrutayisire** [comment]
Hi,

Thank you for your issue. Release 1.19.1 include a fix to support Next.js 14 in Slice Machine.
But be careful you will need to upgrade your Node version, Next 14 now only support Node >= 18.17.

Xavier
