### ISSUE TITLE
[CLI] support setup for Next.js

### ISSUE THREAD

**Issue by hypervillain** [prismicio/slice-machine#12]
CLI command `prismic sm --setup` should bootstrap a Next.js/SliceMachine project. What's expected:

* [x] an API manifest for Next.js (sm-api)
* [x] install default slices library
* [ ] install common dependencies (prismic-javascript, prismis-reactjs)
* [ ] install slices library specific dependencies (from `sm.config.json` file)
* [ ] create/update Next config file with `next-transpile-modules`module
* [ ] create `_document` and `_app` files (se Gists)
* [ ] create a Prismic config file with link/href resolvers and client instantiation
* [ ] create an `sm-resolver` file (see below)

### Files
This configuration assumes essential-slices is used. If not, `pages_app.js` and `pages/_document.js` cannot be created. If they exist or another library was selected, the CLI could not create/update them correctly.

https://gist.github.com/hypervillain/4249f98e1cbd45b62fd7a23d0b8f26ee

**Comment by hypervillain** [comment]
#11 was released in alpha.

Run `npx prismic-cli@alpha sm --setup --framework next` to try it out

**Comment by lihbr** [comment]
Addressed, I'm closing that one!
