### ISSUE TITLE
Feature Request: Edit `first_publication_date`

### ISSUE THREAD

**Issue by barrymichaeldoyle** [prismicio/slice-machine#1212]
### Is your feature request related to a problem? Please describe.

I've been migrating my blog posts from another platform to prismic, but the problem is, as I add blog posts to prismic I can't update the `first_publication_date` to match the actual date it was initially publishes from the previous platform. 

### Describe the solution you'd like

I'd love a way to update the `first_publication_date` for my documents.

### Describe alternatives you've considered

I've considered creating a custom field for this, but that's just so messy and it doesn't play nicely with the fetching API for sorting etc.

**Comment by comeprismic** [comment]
Hi there, 

Thanks for your message and apologize for answering that late. 
We have tracked the issue and will follow-up once we have a solution. But I prefer to tell you that the squads are focused on other topics and priorities at the moment so we can't provide you an expected release date. 

All the best.
