### ISSUE TITLE
Suggestion: Better variations UI

### ISSUE THREAD

**Issue by samuelhorn** [prismicio/slice-machine#123]
Hi!

I know this one is still in the works, and you probably have something in mind already, but cant hurt to share some thoughts right? :)

I was remaking the Slicemachine UI as a practice just for fun, and may have found a good way to show the variations as buttons instead of a dropdown as they are represented now. You could mark the active one with a line or something like i did.

Some benefits are:
- you get a quick overview of all variations.
- you get one click access to edit the name of a variation (not possible yet).
- they become more in sync withe the UI for fields, you can have a button for new variations and such.

![slicemachine-ui-light](https://user-images.githubusercontent.com/2532266/120314069-1fad2780-c2db-11eb-9768-07295ba7c280.png)

Figma link: https://www.figma.com/file/gxz5czYNYCSTmFZBgLSxUf/sm-ui-remake?node-id=0%3A1

**Comment by hypervillain** [comment]
Transitions between variations are really unclear atm, I agree. @Duaner @sadache
