### ISSUE TITLE
Select page type when creating new slice

### ISSUE THREAD

**Issue by Rhymond** [prismicio/slice-machine#1234]
### Is your feature request related to a problem? Please describe.

Currently, the process of adding a new slice to each page type is quite time-consuming and labor-intensive. This often leads to a repetitive and inefficient workflow, especially when dealing with multiple page types.

### Describe the solution you'd like

I propose an enhancement to the slice creation workflow. Ideally, when creating a new slice, there should be an option to select multiple page types to which this slice will be automatically assigned. This feature would significantly streamline the process, reducing the need for manual, repetitive actions.

### Describe alternatives you've considered

As of now, the only method to assign a new slice is to manually navigate through each page type and add the slice individually. This method, while functional, is not optimal in terms of time and ease of use.

### Additional context

I love slice machine <3

**Comment by comeprismic** [comment]
Hey @Rhymond ! 

Thanks a lot for submitting this request. It's actually something that we also think that could be a good addition to the workflow. We even have some designs for that. However I can't guarantee that we will come up with something anytime soon of that front, we have a lot on the plate and would like to stay focused on core feature improvements for the next quarters to come. 

Thanks again, I hope you understand. 

Best, 

Côme, PM of Prismic DevTools
