### ISSUE TITLE
Slicemachine UI shows the wrong type for custom types

### ISSUE THREAD

**Issue by samuelhorn** [prismicio/slice-machine#124]
### Version

- Prismic CLI version (know it by running `prismic --version`): 4.0.1-alpha.10

### Reproduction

Create a custom type, it shows the opposite of "repeatable" in the index.json for that type

### What is expected?

Expected to show "Single type" if "repeatable" is set to false.

### What is actually happening?

Shows "Single type" if "repeatable" is set to true and vice verca.

![ui-error](https://user-images.githubusercontent.com/2532266/121692019-ee490e80-cac7-11eb-906e-495f83976f1d.png)

**Comment by phillysnow** [comment]
We spotted this one too and @hypervillain has implemented the fix already :)

**Comment by a-trost** [comment]
@phillysnow do we know if this issue can be closed? Do we know what the commit was for this @hypervillain ?

**Comment by ReeceM** [comment]
@a-trost 93ae9dd1e259a16d642117dccc0ef03704aee39b 0.1.0-alpha.6 :) and alpha.10 removed the radio buttons 🤣
