### ISSUE TITLE
“Ooops it looks like you are trying to login to Prismic through your terminal, but something has gone wrong”

### ISSUE THREAD

**Issue by snoweeethecat** [prismicio/slice-machine#1259]
I'm using M2 Macbook Air with NodeJS installed directly from their website.

After creating a brand new project, I followed the instructions.
After installing all the necessary files on CLI, it prompted me to open up the login page.

"Browser opened, waiting for you to login..."
It redirected me to "[prismic.io](https://prismic.io/dashboard/cli/login?source=slice-machine&port=xxxx)" but it gave me the error message as shown in my subject title.

I tried to "prismic login" at my terminal but it says "command not found".

Kindly advise how I can resolve this issue.

Thank you.

node -v : v20.10
prismic --version : command not found

 -- Steps to reproduce --
on MBA M2, after logging in to Prismic, select new project, select svelte kit, go to Terminal and copy and paste init@latest --repository [PROJECTNAME] --starter sveltekit-starter-prismic-minimal

After that it says " Browser opened, waiting for you to login..."

Then my Firefox page says “Ooops it looks like you are trying to login to Prismic through your terminal, but something has gone wrong”

My blocker already whitelisted Prismic.io.

✔ Starter copied

ℹ We collect telemetry data to improve user experience.
  Learn more: https://prismic.dev/slice-machine/telemetry

An error occurred with Segment {
  code: 'delivery_failure',
  reason: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11730:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Publisher.send (/Users/[username removed]/.npm/_npx/b6923b01b288b666/node_modules/@segment/analytics-node/dist/cjs/plugins/segmentio/publisher.js:151:34) {
    cause: AggregateError
        at internalConnectMultiple (node:net:1114:18)
        at afterConnectMultiple (node:net:1667:5) {
      code: 'ECONNREFUSED',
      [errors]: [Array]
    }
  },
  ctx: Context {
    attempts: 1,
    event: {
      timestamp: 2024-01-03T06:04:07.715Z,
      integrations: {},
      event: 'SliceMachine Init Start',
      type: 'track',
      properties: [Object],
      context: [Object],
      anonymousId: '6084644a-06ea-4ba9-bbc0-bee7adb6fe13',
      messageId: 'node-next-1704261847715-7d3099a1-10c7-45f8-a671-383571866342',
      _metadata: [Object]
    },
    _id: '3099a110-c7b5-48e6-b138-3571866342b1',
    logger: CoreLogger { _logs: [Array] },
    stats: NullStats { metrics: [] },
    _failedDelivery: { reason: [TypeError] }
  }
}
✔ Detected framework SvelteKit and package manager npm
✔ Began core dependencies installation with npm ... (running in background)
✔ Selected repository canvasproject (flag repository used)
✔ Installed core dependencies with npm
✔ Updated Slice Machine configuration and loaded adapter
⠧ Logging in to Prismic...

**Comment by xrutayisire** [comment]
Hello, sorry for the late answer. 

Did you succeed on the init at the end?
If not, could you try to run `rm ~/.prismic` and retry?

**Comment by snoweeethecat** [comment]
> Hello, sorry for the late answer.
> 
> Did you succeed on the init at the end? If not, could you try to run `rm ~/.prismic` and retry?

Hello,

I managed to resolve the issue.
I'm typing the below for my own reference as well as for anyone who encounters similar issues.

1. Creating a prismicrc dot file at my home directory helps. 
    - I've manually excluded installing the telemetry, based on the guide here https://prismic.dev/slice-machine/telemetry

2. Using Chrome instead of Firefox helps with the initial login, after the CLI installation is completed in Step 1 of the "QuickStart Guide". I'm not sure if it has to do with pop-blocker in Firefox or if its simply thata Prismic works better out of the box with a vanilla install of Chrome.

**Comment by xrutayisire** [comment]
Thank you for your answer 🙌

We will track errors like that one in order to improve our onboarding experience.

I will close the issue now but don't hesitate to reopen if needed.
