### ISSUE TITLE
Adding version 0.1.0 to old sm project fails to show startup page and when storybook isn't installed

### ISSUE THREAD

**Issue by ReeceM** [prismicio/slice-machine#128]
### Version

- Prismic CLI version (know it by running `prismic --version`): *`prismic-cli/4.0.1-alpha.10`*

### Reproduction

Have a project that is on version <= 0.0.46 then manually upgrade to the 0.1.0 version. 

Leaving the defaults from the previous versions folder structure for SliceMachine.

### What is expected?

Be able to run `yarn slicemachine` and access the builder without being presented with a loading icon but an error page or a intro page that shows upgrade information

### What is actually happening?

The page hangs on the failure to find the new `.storybook/main.js` file.  It seems that the other part of auto configuring the new SM lib works for moving things under the .slicemachine directory, but it fails to do so for main.js. 

It also has an unhandled exception which is difficult to figure out, but seems to be related to the fact that the storybook config isn't found.

### Any additional information

There isn't much on upgrading at the moment, but what helped was to look at the new template files to see the difference in the folder structure, which indicated the different storybook file.

*Storybook wasn't installed yet in this instance, which I suspect is possibly the cause of the missing folder. Not sure if it is possible to write that folder and file if missing? Or to catch and notify along with the other storybook not installed error.*

This is the stack trace of the error:

```bash
[slice-machine] Launching server

[slice-machine] Now running on http://localhost:9999 !

[slice-machine] (node:58029) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at parseStorybookConfiguration (../../../lib/env/index.ts:84:31)
    at Object.getEnv (../../../lib/env/index.ts:90:35)
    at handler (../../../../server/src/api/state.ts:81:47)
    at ../../../../server/src/api/index.js:40:25
    at Layer.handle [as handle_request] (ssg/sm/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (ssg/sm/node_modules/express/lib/router/index.js:317:13)
    at ssg/sm/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (ssg/sm/node_modules/express/lib/router/index.js:335:12)
    at next (ssg/sm/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (ssg/sm/node_modules/express/lib/router/index.js:174:3)
(Use `node --trace-warnings ...` to show where the warning was created)

[slice-machine] (node:58029) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:58029) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by hypervillain** [comment]
Yeah, Storybook is required to be installed at the moment. It should not, i agree. To get around this specific issue, create a `.storybook/main.js` file and just write `getStoriesPaths` there. It's the string we look for when generating the env.

@Duaner wdyt?

**Comment by ReeceM** [comment]
> Yeah, Storybook is required to be installed at the moment. It should not, i agree. To get around this specific issue, create a `.storybook/main.js` file and just write `getStoriesPaths` there. It's the string we look for when generating the env.

In the end I did create that file after looking at the template repositories to find the file to create, after that it did work. I hadn't fully installed storybook either.

At that point then the new 'You've upgraded' page shows that informs you the new `.slicemachine` directory has been migrated to match the latest version. Then the second thing suggested is to add the below to `.storybook/main.js`

```javascript
const { getStoriesPaths } = require('slice-machine-ui/helpers/storybook')

module.exports = {
  stories: [...getStoriesPaths(), /*...*/]
}
```

That fixed it, but maybe that page should show even if it isn't found yet? I had a screenshot of that page and lost it, but will try get it again to make sure it's the right thing I was seeing...


Also, I noticed, the above is suggested to be placed in the main.js file, then when running the storybook install command from `prismic sm` it changes it to the below: 

```javascript
module.exports = {
  stories: ["../slices/**/*.stories.[tj]s","../.slicemachine/assets/slices/**/*.stories.[tj]s"]
}
```

Kinda going back on itself to the old one? Or which is the newer one?

**Comment by ReeceM** [comment]
Okay, on the above, its the function `LacksStorybookConf` in `slice-machine-ui/components/UnrecoverableErrors/index.js`

**Comment by ReeceM** [comment]
I was thinking that this might solve the problem of both the new format not being present and also the missing directory if it isn't added yet. 

One option could be the one below:
```ts
function parseStorybookConfiguration(cwd: string) {
  try {
    const pathsToFile = [path.join(cwd, '.storybook/main.js'), path.join(cwd, 'nuxt.config.js')]
    const f = Files.readFirstOf(pathsToFile)(v => v)
    return (f?.value as string).includes('getStoriesPaths')
  } catch (err) {
    return false;
  }
}
```

Or because it's TypeScript:
```typescript
function parseStorybookConfiguration(cwd: string) {
  const pathsToFile = [path.join(cwd, '.storybook/main.js'), path.join(cwd, 'nuxt.config.js')]
  const f = Files.readFirstOf(pathsToFile)(v => v)
  return (f?.value as string)?.includes('getStoriesPaths')
}
```

The latter might be just better to take advantage of the language ? This way the error page shows when the storybook directory is misconfigured or not setup in the `main.js` file correctly. 

I would make the edit, but not sure if the `with-custom-types` branch is the right one? I tested the changes locally in the project to see, by adding the compiled version to the built index.js  file.

```javascript
function parseStorybookConfiguration(cwd) {
    const pathsToFile = [path_1.default.join(cwd, '.storybook/main.js'), path_1.default.join(cwd, 'nuxt.config.js')];
    const f = files_1.default.readFirstOf(pathsToFile)(v => v);
    var _a;
    return (_a = f === null || f === void 0 ? void 0 : f.value) === null || _a === void 0 ? void 0 : _a.includes('getStoriesPaths');
}
```

**Comment by ReeceM** [comment]
Resolved in latest alpha 👍
