### ISSUE TITLE
Live Preview feature is adding a big height to our preview Slice 

### ISSUE THREAD

**Issue by fmontada** [prismicio/slice-machine#1299]
### Versions

- slice-machine-ui:  1.24.0
- node:  v18.17.0

### Reproduction

![image](https://github.com/prismicio/slice-machine/assets/9787595/41c6b475-ca6c-4e28-899f-820fe9be6ecd)

<details open>
<summary>Additional Details</summary>
<be>
We are testing the Live Preview feature but it is adding a big height to our preview Slice-Preview, in this case 1065.99px check the image below:

</details>

**Comment by comeprismic** [comment]
Hello! 
Thanks for the feedback and the issue raised. 
The Prismic Page builder is aware of the issue and will work on a fix. Though, we cannot commit on a release date for now. We will come back to you when it is fixed.
