### ISSUE TITLE
unable to upload images from Image Library 

### ISSUE THREAD

**Issue by ranaharoon3222** [prismicio/slice-machine#1300]
### Versions

- slice-machine-ui: 1.24.0
- node: 20.9.0

### Reproduction

![image](https://github.com/prismicio/slice-machine/assets/41114075/118b3feb-f674-4eb2-9942-065aee8575bc)

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

normal workflow go to simulator and replace image above error will  be shown
![image](https://github.com/prismicio/slice-machine/assets/41114075/7919c7f8-a834-4287-ac77-6f733c9da8f9)

### What is expected?

normal media library to upload images

### What is actually happening?

error on media library

**Comment by xrutayisire** [comment]
Hi,

Thank you for the bug report.
We are currently working on a fix and will release a version of Slice Machine with it soon.

Just know that we don't support upload from media library and only the unsplash tab should be visible. You can click on it even with this error to continue working.

Xavier

**Comment by xrutayisire** [comment]
Error fixed in the last version of Slice Machine 1.24.1.
