### ISSUE TITLE
Nuxt dev server crash when login on slicemachine 

### ISSUE THREAD

**Issue by Applelo** [prismicio/slice-machine#1307]
### Versions

- slice-machine-ui: 1.24.1
- node: v20.11.0

### Reproduction

I can't provide a reproduction, it's only happen on my colleague device. It tells me he doesn't change a thing on his configuaration since it was working the last time on the project. So it will be a hard to reproduct/debug 😞 
We tried to remove node_modules, reinstall modules, remove .prismic config: Not of this was working. 

> Note: our project have two prismic environnements.

<details>
<summary>Additional Details</summary>
<br>

```json

{
"dependencies": {
    "@nuxt/image": "1.3.0",
    "@nuxtjs/fontaine": "^0.4.1",
    "@nuxtjs/i18n": "8.1.1",
    "@nuxtjs/prismic": "^3.1.0",
    "@nuxtjs/turnstile": "^0.6.3",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "@pinia/nuxt": "^0.5.1",
    "@slicemachine/adapter-nuxt": "^0.3.36",
    "@vee-validate/i18n": "^4.12.5",
    "@vee-validate/nuxt": "^4.12.5",
    "@vee-validate/zod": "^4.12.5",
    "@vueuse/core": "^10.8.0",
    "@vueuse/nuxt": "^10.8.0",
    "basic-auth": "^2.0.1",
    "compotes": "^0.9.2",
    "focus-trap": "^7.5.4",
    "foundation-sites": "^6.8.1",
    "jsonwebtoken": "^9.0.2",
    "lodash.capitalize": "^4.2.1",
    "lodash.chunk": "^4.2.0",
    "lru-cache": "^10.2.0",
    "motion-ui": "^2.0.5",
    "nodemailer": "^6.9.10",
    "nuxt": "3.10.2",
    "nuxt-delay-hydration": "^1.3.3",
    "nuxt-graphql-middleware": "4.0.0",
    "nuxt-lazy-hydrate": "^1.0.0",
    "nuxt-multi-cache": "^3.1.1",
    "nuxt-security": "1.1.2",
    "photoswipe": "^5.4.3",
    "set-cookie-parser": "^2.6.0",
    "swiper": "^11.0.6",
    "uuid": "^9.0.1",
    "vee-validate": "^4.12.5",
    "what-input": "^5.2.12",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@antfu/eslint-config": "2.6.4",
    "@nuxtjs/eslint-config-typescript": "^12.1.0",
    "@nuxtjs/html-validator": "^1.6.0",
    "@spiriit/vite-plugin-svg-spritemap": "^2.2.4",
    "@types/basic-auth": "^1.1.8",
    "@types/jsonwebtoken": "^9.0.5",
    "@types/lodash.capitalize": "^4.2.9",
    "@types/lodash.chunk": "^4.2.9",
    "@types/nodemailer": "^6.4.14",
    "@types/request-ip": "^0.0.41",
    "@types/set-cookie-parser": "^2.4.7",
    "eslint": "^8.56.0",
    "maildev": "^2.1.0",
    "sass": "npm:sass-embedded@1.71.1",
    "slice-machine-ui": "^1.24.1",
    "typescript": "^5.3.3"
  }
}
```

</details>

### Steps to reproduce

Launch a Nuxt 3 project with `nuxt dev` and launch slicemachine with `start-slicemachine`. The user logged in on prismic. 

### What is expected?

To not create a loop on nuxt dev server by editing the .env file.

### What is actually happening?

It seems like the .env is edited by prismic slicemachine and the nuxt server is triggering several restart causing crash of nuxt dev server and making prismic slicemachine unresponding.

![image](https://github.com/prismicio/slice-machine/assets/7613286/20034bc7-a557-4658-9495-47f3ec88cecd)

**Comment by comeprismic** [comment]
Hello, 
Thanks for submitting the issue. To be sure we understand correctly, how blocked are you on the project? Does it prevent you from working on your project or do you have a workaround?

**Comment by Applelo** [comment]
Hi, we are not blocked. My colleague closes the nuxt dev server when is using slicemachine logged on it. When he needs to work on nuxt, he logs out from slicemachine.

**Comment by comeprismic** [comment]
Hi! Thanks for your answer, we will investigate your issue by the beginning of next week.

**Comment by angeloashmore** [comment]
Hi @Applelo, thanks for the detailed report! As expected, I am having trouble reproducing this issue.

For some background info, Slice Machine touches the `.env` file to store the active Prismic environment. When you change environments in Slice Machine, the `.env` file should either update `NUXT_PUBLIC_PRISMIC_ENVIRONMENT` with the selected environment or delete `NUXT_PUBLIC_PRISMIC_ENVIRONMENT` if the production environment is selected.

Considering this is only happening on your colleague's machine and `.env` is typically machine-specific, it's possible their `.env` file has something unusual.

Could you have them try deleting `.env`, repopulating it with the same `.env` you have on your working machine, and starting Slice Machine again? And could you let us know what happens?

Thank you!

**Comment by Applelo** [comment]
Thank you for your time. I close the issue because my collegue doesn't work anymore on my prismic project and I was unable to reproduce the bug. Maybe I will reopen it if it reappear ;)

**Comment by angeloashmore** [comment]
Thanks for the update, @Applelo. Indeed, if you come across the issue again, please let us know and we will investigate. 🙂
