### ISSUE TITLE
[slice-machine-ui@0.1.0-alpha.6]: Released package is way too large (over 100 MiB in size)

### ISSUE THREAD

**Issue by zalanlevai** [prismicio/slice-machine#134]
### Version

- Prismic CLI version: `prismic-cli/4.0.1-alpha.10 wsl-x64 node-v16.3.0`
- SliceMachine version: `slice-machine-ui@0.1.0-alpha.6`

#### yarn

Add `slice-machine-ui@0.1.0-alpha.6` to a bare yarn 2 package:
```sh
mkdir slice-machine-package-size-yarn
cd slice-machine-package-size-yarn
yarn init
yarn set version berry
echo "nodeLinker: node-modules" >> .yarnrc.yml
yarn add -D slice-machine-ui@0.1.0-alpha.6
```

Inspect package size in `.yarn/cache`:
```sh
du -h .yarn/cache/slice-machine-ui-npm-0.1.0-alpha.6-*.zip
```

#### npm

Add `slice-machine-ui@0.1.0-alpha.6` to a bare npm package:
```sh
mkdir slice-machine-package-size-npm
cd slice-machine-package-size-npm
npm init
npm install -D slice-machine-ui@0.1.0-alpha.6
```

Inspect package size in `node_modules`:
```sh
du -h node_modules/slice-machine-ui
```

### What is expected?

Yarn 2 compresses and caches dependency sources in the project's `.yarn/cache` directory. In this format, most runtime dependencies are a few KiB and developer tools do not exceed 10 MiB. As such, `slice-machine-ui` should be at most a few MiB when cached by yarn 2.

### What is actually happening?

`slice-machine-ui` is considerably larger than any other development dependency. In the above mentioned `.yarn/cache` format, `slice-machine-ui@0.1.0-alpha.6` sits at 136 MiB, which is many times larger than any other development tool in the workspace. This is also reflected in install times amongst others.

When using npm, the equivalent `node_modules/slice-machine-ui` is 585 MiB.

### Any additional information

`slice-machine-ui@0.1.0-alpha.6` seems to have been released with ALL of its build artifacts packaged with the source, as would be done with an application, but this is not really appropriate for dependencies. This is all based on what I found inspecting the [yarn cache archive of the package](https://github.com/prismicio/slice-machine/files/6696986/slice-machine-ui-zip-contents.txt). [npm's `node_modules`](https://github.com/prismicio/slice-machine/files/6696987/slice-machine-ui-npm-du.txt) exhibits similar behavior.

The current size of the package is very limiting and has caused some issues in our pipeline. Yarn 2's dependency cache is typically uploaded to repositories to amend lockfiles for improved CI/CD performance and other developer experience improvements. We currently have to exclude the package from being uploaded to our repository, which accounts for more than half of our dependency cache on a moderately sized monorepo.
```gitignore
## Yarn Berry
.yarn/*
!.yarn/cache
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions

## Oversized dependencies
.yarn/cache/slice-machine-ui-npm-0.1.0-alpha.6-40952b27f7-5861a0b0b9.zip
```
The size of the package might also be related to incomplete dependency installations in Docker containers, although we are still investigating that.

For reference, in our production monorepo, these are the largest dependencies and their sizes ([see disk usage of all cache files](https://github.com/prismicio/slice-machine/files/6696981/yarn-cache-du.txt)):
![image](https://user-images.githubusercontent.com/12102131/122988238-cdbf6500-d3a1-11eb-9369-bca9b7f867ab.png)

BTW, thank you for the awesome work you have been doing on SliceMachine and Prismic's JavaScript/TypeScript SDK! We are currently running all of your latest alphas and really appreciate the new direction you are taking your libraries.

**Comment by lihbr** [comment]
Hey @zalanlevai, thanks for the detailed report, we will investigate! I'm also quite excited about the work moving forward on our other kits ☺️

@hypervillain I started a bit and looks like already `./build/client` doesn't need to be shipped, already shaving 393 MB out of the 461 MB it takes on my disk, last big bite remaining being the `./out` directory (55.7 MB on my disk) I'm not sure what we can share from it though, being the built Next webapp 🤔

**Comment by ReeceM** [comment]
I have been watching my node_modules folder and also found the final size is quite large, for the alphas the `node_modules` folder is 900MB+ (puppeteer only 339MB of that, which is understandable) 

But having more than 4 or 5 slice-machine projects gets a bit odd, haven't tried using `pnpm` though

The build client cache files have a bunch of faker data (one file is 15MB) in there for all the languages, not sure if it can be trimmed to 'english' only?

 Because if someone has custom mock values they would technically type in their home language. 

I always thought it was on my machine that there was something odd.

**Comment by hypervillain** [comment]
Good catch, we introduced a wrong build step when moving to TypeScript.
This should be better-ish https://www.npmjs.com/package/slice-machine-ui/v/0.1.0-alpha.9

**Comment by ReeceM** [comment]
I can confirm the size is now `16.7MB` for `slice-machine-ui` for myself and the size of the modules file is total of `496MB`, a lot has been trimmed off 🎉 

Thought I might share that

**Comment by zalanlevai** [comment]
After a simple dependency upgrade, I can also confirm the huge size reduction with `slice-machine-ui@0.1.0-alpha.9` and that SliceMachine still works as before.

![image](https://user-images.githubusercontent.com/12102131/123556204-21f38c00-d78a-11eb-9f26-cb39777e0a9d.png)

As far as we are concerned, the issue can be closed now. 😊 Feel free to reopen if there are any other obvious improvements that could be made.
