### ISSUE TITLE
Slice migration causing SliceZone issues due to slice_type field

### ISSUE THREAD

**Issue by crcollver** [prismicio/slice-machine#1373]
I'm not sure if this a bug necessarily, but I feel like it is kind of an unexpected behavior.  I created a forum post [here](https://community.prismic.io/t/migrating-legacy-slices-to-slice-machine-question-on-legacy-slice-names/15901), but I realize slice migration is still in beta so there might not be as much traffic for the topic.  I apologize for the duplication.

### Versions

- slice-machine-ui: 1.26.0
- node: 21.7.2

### Reproduction

<details open>
<summary>Additional Details</summary>
- next: 14.1.4
<br>
- @prismicio/client: 7.5.0
<br>
- @prismicio/next: 1.5.0
<br>
- @prismicio/react: 2.7.4
<br>
- @prismicio/slice-simulator-react: 0.2.3
<br>
- @slicemachine/adapter-next: 0.3.38
</details>

### Steps to reproduce

1. My repository is using legacy slices, and I chose one page to try the slice migration tool on.
2. I've successfully migrated all of my slices in slice machine for this page and used the default names it gave me.  For example "SimpleSection".  Slice Machine generated the `index.ts` file which exports all of my slices.
```javascript
// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  SimpleSection: dynamic(() => import("./SimpleSection")),
};
```
3. I've pushed my slice migration changes up to Prismic, ran my NextJS dev server, and navigated to the migrated page.
4. I get the following error in my console and the slices will not render.
```
[SliceZone] Could not find a component for Slice type "simple_section"
```

### What is expected?

Either slice machine will use the existing slice type name during migration or it would update the references in the repository correctly after pushing the changes.  

Do I need to republish the page?  If this is the case, then I wasn't aware this was required.

### What is actually happening?

My Prismic query is returning the following `slice_type` value which causes the error I'm seeing in the console.
```
{
  ...,
  slice_type: 'simple_section'
}
```
Changing the auto-generated `index.ts` file to match the snake case that is returned from Prismic solves the issue.  However, I do not want to manually edit this file per instruction.  I am also unsure if editing the generated JSON from slice machine in order to change the slice name is a good idea either.

I could manually map the object that is being passed to SliceZone, but that does not match documentation and is rather inconvenient because slice machine generates this for me.

**Comment by comeprismic** [comment]
Hi, 

I'm closing this issue since it has been answered in the forum [here](https://community.prismic.io/t/migrating-legacy-slices-to-slice-machine-question-on-legacy-slice-names/15901/5). 

Best
