### ISSUE TITLE
While creating my porfolio I encounterd a bug which is, when i try to add image in my slice from prismic.io  and choose select Image from unsplash  and try to search  any image by typing its name (for example tech) the site automatically reloads and sends me back to main page.  drive link of video - https://drive.google.com/file/d/1uXcUmew4MhKzRaxUbC_gHgQwauKmXhDo/view?usp=sharing

### ISSUE THREAD

**Issue by JiteshK1** [prismicio/slice-machine#1378]
### Versions

- slice-machine-ui: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

**Comment by xrutayisire** [comment]
Hi,

Sorry for the late answer, this is a bug related to Page Builder and not directly Slice Machine. We transferred your issue to the corresponding team and they will prioritize it.

Thank you for the report 🙂
