### ISSUE TITLE
Slice machine stops working when converting generated files to .ts(x)

### ISSUE THREAD

**Issue by amosbastian** [prismicio/slice-machine#138]
### Version

```
prismic-cli/4.0.1-alpha.12
```

### Reproduction

1. Generate a slice
2. Rename `.js(x)` files to `.ts(x)`
3. It works until you stop slice machine and run it again:
```
UnhandledPromiseRejectionWarning: Error: ENOTDIR: not a directory, lstat '/Users/amosbastian/Development/xxx/src/slices/index.ts/model.json'
```

### What is expected?

I want to use TypeScript so I want to be able to rename `js(x)` files to `ts(x)` without a problem.

### What is actually happening?

It works fine until restarting slice machine, then it won't load the slices anymore until I change all `ts(x)` files back to `js(x)` files.

**Comment by lihbr** [comment]
Hey, thanks for the report @amosbastian!

@hypervillain 👀

**Comment by christianrybe** [comment]
Interestingly this seems not to be an issue for me with slice-machine `0.1.0-beta.1`

**Comment by amosbastian** [comment]
I'm using `slice-machne-ui` version `^0.1.0-alpha.13` just fyi. It would be great to just have an option to use TypeScript as well.

**Comment by lihbr** [comment]
Hey @amosbastian, I need to check on our side, it appears version `0.1.0-beta.1` is the most up-to-date pre-release of `slice-machine-ui`.

Can you confirm the issue on that version? Let us know if anything!

**Comment by hypervillain** [comment]
The issue will still be there on beta. I'll take a look this week @amosbastian thanks for reporting this

**Comment by hypervillain** [comment]
Hey @amosbastian can you upgrade to slice-machine-ui@0.1.0-beta.2 ?
We spotted the issue and it should be fixed now. Thanks for your patience!
Feel free to re-open
