### ISSUE TITLE
Cant create slice

### ISSUE THREAD

**Issue by Calvinkirabo** [prismicio/slice-machine#1397]
![Screenshot from 2024-07-09 14-20-35](https://github.com/prismicio/slice-machine/assets/106669343/faab609c-5605-4e51-bd60-c44835b9eb08)

### Versions

- slice-machine-ui: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

**Comment by Calvinkirabo** [comment]
![Screenshot from 2024-07-09 14-26-17](https://github.com/prismicio/slice-machine/assets/106669343/c3d3d190-52a1-4888-b519-ac45e0b92199)

**Comment by comeprismic** [comment]
Hey, 

Can you tell us which version of Slice Machine and adapter you have? Did you manage to create other slices than this one or it's failing everytime? Does Page Type creation work on your side? 

Thanks in advance for you answers. feel free to send also screenshots of any contextual information you have on your project for us to able to understand the issue.

**Comment by Calvinkirabo** [comment]
hi 
I'm using the slice machine version v2.2.
I wasn't able to create new slices and it was failing every time
. The only slice i had was the default RichText slice 
which i was able to delete but i couldn't re-create it dut to the original problem.  Page type doesn't also work it doesnt save my pages . 
Pleasse let me know what i can do
![Screenshot from 2024-07-11 09-45-18](https://github.com/prismicio/slice-machine/assets/106669343/1a8af160-4337-4309-a857-b15958405275)
![Screenshot from 2024-07-11 09-41-05](https://github.com/prismicio/slice-machine/assets/106669343/62b0b484-ed5d-4025-83d2-b61e1f1e8903)
![Screenshot from 2024-07-11 09-41-49](https://github.com/prismicio/slice-machine/assets/106669343/88ce5428-197e-4ae5-b213-9e956bc5e39e)

**Comment by comeprismic** [comment]
Hi can you send us the errors you see in your browser console and your terminal? 
Aditionnally, the best for us to reproduce and fix the issue would be to have a Github repository reproducing the issue.

**Comment by comeprismic** [comment]
Hello, I will close the issue for now. Feel free to reopen if the problems comes back.
