### ISSUE TITLE
RFC: Automatically detect framework

### ISSUE THREAD

**Issue by arnaudlewis** [prismicio/slice-machine#14]
### Context
While running slicemachine, now that we're about to support Next.js in addition to nuxt and probably more technologies soon enough, we'd like to make the journey as easy as possible to the user.
While running commands like `setup` or `create-slice` we need that information to manipulate the filesystem but it seems like an obvious info for the user and it should be detected automatically.

### Solution
The considered solution would be to simply parse the package.json and detect the packages that could help us identify which framework is currently setup in the project.
This idea comes from StoryBook that does this already and it seems like a simple solution.
As a fallback, the user will have the possibility to specify an additional parameter `--framework` to specify it manually.

### Implementation
- We setup a list of supported frameworks
- We declare a test per framework based on files/dependencies/devDependencies/peerDependencies
- We execute these test if `--framework` is not specified or not valid

**Comment by arnaudlewis** [comment]
First implementation in the context of adding the support of Next.js in slicemachine; https://github.com/prismicio/prismic-cli/commit/9dc97a9f770c924d2ed8a723c006275c28638c6d

**Comment by Duaner** [comment]
This is implemented, can we close this?
