### ISSUE TITLE
Generated sm-resolver.js does not work properly with custom location of slices library

### ISSUE THREAD

**Issue by amosbastian** [prismicio/slice-machine#142]
### Versions

- slice-machine-ui: 0.1.0-alpha.13
- node: v14.16.1

### Steps to reproduce

* Run `prismic sm --create-slice`
* Select non-default folder (e.g. `src/slices`) (btw it should give me an option to select my custom location instead of having to type it each time)
* Generated `sm-resolver.js` tries to import slices like this: `import * as Src/slices from './src/slices'`

### What is expected?

It should not base the name of the import off the location of the library and instead just import like usual:

```
import * as Slices from './src/slices';
```

### What is actually happening?

It is generating the following import:

```
import * as Src/slices from './src/slices';
```

which is not a valid import.

**Comment by lihbr** [comment]
Thanks for the report @amosbastian and sorry for the delay!

@hypervillain can you have a look?

**Comment by hypervillain** [comment]
We're on it

**Comment by hypervillain** [comment]
The should be fixed with the latest version of next-slicezone. Thanks for reaching out!
