### ISSUE TITLE
Storybook fails to load with slice-machine-ui 0.1.0-beta.1

### ISSUE THREAD

**Issue by christianrybe** [prismicio/slice-machine#143]
### Versions

- slice-machine-ui: 0.1.0-beta.1
- node: v14.15.3

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

Here is my `package.json` file

```
{
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "eslint . --ext js,jsx,ts,tsx --cache --fix",
    "prepare": "husky install",
    "type-check": "tsc --project tsconfig.json --pretty --noEmit",
    "test": "echo 'no tests to execute'",
    "slicemachine": "start-slicemachine --port 9999",
    "storybook": "start-storybook -p 8888",
    "build-storybook": "build-storybook"
  },
  "cacheDirectories": [
    ".next/cache"
  ],
  "dependencies": {
    "essential-slices": "^1.0.4",
    "next": "11.0.1",
    "next-slicezone": "^0.1.0",
    "next-transpile-modules": "^8.0.0",
    "prismic-javascript": "^3.0.2",
    "prismic-reactjs": "^1.3.4",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "styled-components": "^5.3.0",
    "theme-ui": "^0.10.0"
  },
  "devDependencies": {
    "@storybook/react": "^6.1.21",
    "@types/react": "17.0.13",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "babel-loader": "^8.2.2",
    "babel-plugin-react-require": "^3.1.3",
    "eslint": "7.30.0",
    "eslint-config-next": "11.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "husky": "^7.0.0",
    "lint-staged": ">=10",
    "prettier": "2.3.2",
    "slice-machine-ui": "^0.1.0-beta.1",
    "typescript": "4.3.5"
  }
}
```
</details>

### Steps to reproduce

1. Initialise a repo with prismic with `prismic sm --setup`
2. Update `slice-machine-ui` dependency to use 0.1.0-beta.1
3. Run slice machine and storybook 
4. Go to storybook at localhost:8888

### What is expected?

Storybook loads and works correctly.

### What is actually happening?

The page never loads any data, you can only see the spinner. There are no additional logs in the terminal, where storybook has been run. 

I've created a new slice to see if it helps storybook to load, but this didn't help.

**Comment by a-trost** [comment]
Hey @rybarczykchris ! Sorry you're hitting this issue, I think I faced something similar and upgrading storybook fixed it for me. 

Specifically I upgraded to 
```
"@storybook/react": "^6.2.9",
```

**Comment by christianrybe** [comment]
Thanks @a-trost ! Good call! 🙂 `6.2.9` did the trick, although previously I had a later version `6.3.4` and I did not work... 🤔
