### ISSUE TITLE
Issue with Viewing New Slices in Prismic

### ISSUE THREAD

**Issue by rohan-takmoge** [prismicio/slice-machine#1446]
Hi,

I’m encountering an issue with Prismic where I’m unable to see newly created slices in my content types. I’ve checked the Slice Zone setup, confirmed the slices are published, and tried refreshing the API browser, but the new slices still aren't appearing.

Could you please guide me on what might be causing this issue or any additional steps I should take?

**Comment by phillysnow** [comment]
Hi Rohan,

I'll be really happy to help. This doesn't sound like a Slice Machine issue, though, so can you send me a message in our support portal, and we can look at your repository together?
https://prismic.atlassian.net/servicedesk/customer/portal/1/create/130

Thanks.

**Comment by phillysnow** [comment]
I sent him to the support portal.
