### ISSUE TITLE
Add ability to change viewport for generated Storybook screenshots

### ISSUE THREAD

**Issue by amosbastian** [prismicio/slice-machine#147]
### Is your feature request related to a problem? Please describe.

I want the generated screenshots to use a different viewport. I have a breakpoint set at 1280px, while the viewport used to generate the screenshots is [hardcoded to 1200px](https://github.com/prismicio/slice-machine/blob/ff1a330dcbeb7f3eb5300a0bd30f0d8fc4772861/packages/slice-machine/server/api/common/utils.js#L14-L17), so it generates screenshots for my tablet and laptop breakpoints.

### Describe the solution you'd like

I would like to be able to change the viewport myself... not sure what the best place to add this is, though. Maybe add a settings page in the SliceMachine UI.

**Comment by comeprismic** [comment]
Hello, 
I'm closing this issue now that we have released our Slice Simulator. Thanks again for writing here, feel free to reach out again anytime you find improvement areas :)
