### ISSUE TITLE
Pre-transform error: Failed to resolve import ../lib/logger

### ISSUE THREAD

**Issue by yuhaoboris** [prismicio/slice-machine#1498]
### Versions

- slice-machine-ui: 2.10.5
- node: v20.16.0

### Reproduction
I just following the Prismic Nuxt documentation:
1. Init a Nuxt project by running command `npx nuxi@latest init prismic-nuxt-demo`
2. run the setup command: `npx @slicemachine.init@latest`

After doing these, i start project by running `npm run dev`

Finally i got this error message:
```
ERROR  Pre-transform error: Failed to resolve import "../lib/logger" from "node_modules/@nuxtjs/prismic/dist/runtime/plugin.js?v=9ee3048e". Does the file exist?
```

I'm 100% make sure following the documentation steps, and try over three times and still can not run the project successfully.
I’m not sure if I’m the only one experiencing this issue.

#### Initial Nuxt project
`npx nuxi@latest init <project-name>`
#### Install dependencies
`cd <project-name> && npm install`
#### Initial slice machine
`npx @slicemachine/init@latest`
#### Start development server
`npm run dev`

### What is expected?
Fix the incorrect import

### What is actually happening?
open http://localhost:3000 in browser, the terminal got these error message
![截屏2024-12-05 10 29 23](https://github.com/user-attachments/assets/4701948b-9921-4428-b95d-c88c4caaff27)

**Comment by lihbr** [comment]
Hi there, thanks for reporting this! This should be fixed with `@nuxtjs/prismic` v3.4.5 that was released just now. It was an issue introduced with v3.4.4 related to a compiling mistake on the module 🙏
