### ISSUE TITLE
[SliceMachine/handleFrameworks] Unable to fetch manifests

### ISSUE THREAD

**Issue by fofiu** [prismicio/slice-machine#17]
Brand new project following your tutorial and it errors out here. What to do?
```
 prismic sm --setup
✔ Downloading framework definitions

 ERROR  [SliceMachine/handleFrameworks] Unable to fetch manifests. Error code: 502                                               10:20:32

ℹ Exiting...  
```

**Comment by hypervillain** [comment]
Hey @cfofiu, I just pushed a fix for this, could you give it another try?

**Comment by fofiu** [comment]
Works now! Thanks! Would be nice (probably sooner than later) to allow people to choose an existing repo rather than create a new one every time when running `prismic sm --setup`.

Other than that, awesome job! You guys rock!

**Comment by hypervillain** [comment]
Great! I think you can pass the argument `--no-prismic` to prevent the
setup command from creating a new repo.
You would then have to manually update your Nuxt config of course 😊
