### ISSUE TITLE
nuxt nitro generated imports failing at `sm-commons/utils/str` after nuxt bridge upgrade

### ISSUE THREAD

**Issue by eveningforgery** [prismicio/slice-machine#191]
### Versions

- slice-machine-ui: 0.1.0
- sm-commons: 0.0.23
- node: 16.11.1
- @nuxtjs/bridge: npm:@nuxtjs/bridge-edge (3.0.0-27234503.d5127e9)
- nuxt-edge: latest (2.16.0-27226092.034b9901)

<details open>
<summary>Additional Details</summary>
<br>

Logs:
<pre>
<code>
ℹ Full static generation activated                                                           14:31:48
ℹ Nitro preset is server                                                                     14:31:48
ℹ Cleaning up .output                                                                        14:31:48
ℹ Generating output directory: public/                                                       14:31:49
start Building server...                                                                     14:31:49
start Writing server bundle...                                                               14:31:55
✔ Server built                                                                               14:31:57
  ├─ node_modules/.cache/nuxt/nitro/index.mjs.map (1.33 MB) (149 kB gzip)
  └─ node_modules/.cache/nuxt/nitro/index.mjs (1.61 MB) (346 kB gzip)
Σ Total size: 2.94 MB (495 kB gzip)
 FATAL  [worker] Cannot find module '/Users/usr/Documents/Github/project/node_modules/sm-commons/utils/str' imported from /Users/usr/Documents/Github/project/node_modules/.cache/nuxt/nitro/index.mjs
Did you mean to import sm-commons/utils/str.js?

  Did you mean to import sm-commons/utils/str.js?
  at new NodeError (node:internal/errors:371:5)
  at finalizeResolution (node:internal/modules/esm/resolve:416:11)
  at moduleResolve (node:internal/modules/esm/resolve:932:10)
  at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:1044:11)
  at Loader.resolve (node:internal/modules/esm/loader:89:40)
  at Loader.getModuleJob (node:internal/modules/esm/loader:242:28)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)

   ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                 │
   │   ✖ Nuxt Fatal Error                                                                                            │
   │                                                                                                                 │
   │   Error: [worker] Cannot find module                                                                            │
   │   '/Users/usr/Documents/Github/project/node_modules/sm-commons/utils/str' imported from   │
   │   /Users/usr/Documents/Github/project/node_modules/.cache/nuxt/nitro/index.mjs            │
   │   Did you mean to import sm-commons/utils/str.js?                                                               │
   │                                                                                                                 │
   ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
</code>
</pre>
</details>

### Steps to reproduce
Upgrade an existing nuxt project using slicemachine following nuxt bridge guide:
https://v3.nuxtjs.org/getting-started/bridge/

`yarn dev` works as intended
`yarn generate` fails after nitro server built

### What is expected?
Generation should not throw error at sm-commons imports

### What is actually happening?
Nitro generates `nodes_modules/.cache/nuxt/nitro/index.mjs`, adds the import of `sm-commons`, then throws error at line:
```mjs
import * as str from 'sm-commons/utils/str';
```

**Comment by LouieRichardson99** [comment]
Did you find any solution to this error? 
Currently experiencing the exact same error on build.

**Comment by lihbr** [comment]
Hey there, I'm really sorry for the delay here.

Looks like it's related to that one: nuxt/bridge#159

Updating the `build.transpile` array fixed it for me: https://v3.nuxtjs.org/concepts/esm/#transpiling-libraries, you might also need to add other dependencies that throw similar errors to that array~

Let us know how it goes!

**Comment by LouieRichardson99** [comment]
Thank you for the reply @lihbr 

Currently my build.transpile array is ['vue-slicezone', 'nuxt-sm'].
Is there anything I am missing?

**Comment by lihbr** [comment]
You welcome, just also add `sm-commons` to it and you should be fine :)

**Comment by LouieRichardson99** [comment]
> You welcome, just also add `sm-commons` to it and you should be fine :)

It's working! I've been trying to figure this out all afternoon. 😆 

Thank you!

**Comment by sr-skillmore** [comment]
> Hey there, I'm really sorry for the delay here.
> 
> Looks like it's related to that one: [nuxt/bridge#159](https://github.com/nuxt/bridge/issues/159)
> 
> Updating the `build.transpile` array fixed it for me: https://v3.nuxtjs.org/concepts/esm/#transpiling-libraries, you might also need to add other dependencies that throw similar errors to that array~
> 
> Let us know how it goes!

The link https://nuxt.com/docs/concepts/esm/#transpiling-libraries throws a 404 Page Not Found
