### ISSUE TITLE
`slice-machine-ui` relies on `node-fetch` but doesn't declare it as a dependency, causing dependencies mismatch

### ISSUE THREAD

**Issue by lihbr** [prismicio/slice-machine#216]
### Versions

- slice-machine-ui: v0.1.1 & v0.1.0
- node: 16.6.0

### What is going on

Currently `slice-machine-ui` [doesn't declare `node-fetch` as a dependency](https://github.com/prismicio/slice-machine/blob/master/packages/slice-machine/package.json#L106) but [relies on it](https://github.com/prismicio/slice-machine/blob/master/packages/slice-machine/start/index.js#L25).

`node-fetch` being a very common dependency, it's likely there. However because it's common `npm` tries to duplicate it when installing dependencies.

Slice Machine expects version 2 of `node-fetch` to be available, however the latest version of `node-fetch` is now an ESM package only. This causes when `npm` prefers to dedupe `node-fetch@3` instead of `node-fatch@2`, causing `slice-machine-ui` to fail.

<details>
<summary><code>node-fetch@3</code> being deduped:</summary>
<br>

![image](https://user-images.githubusercontent.com/25330882/140501183-c8f48380-57f5-438e-8d57-5bc4e3853bd2.png)

</details>

<details>
<summary><code>slice-machine-ui</code> failing because of it:</summary>
<br>

![image](https://user-images.githubusercontent.com/25330882/140501300-dcf46e35-1d0d-46c1-b076-b76b15ee0eaf.png)

</details>

### How to fix

Install `node-fetch@2` as a dependency of `slice-machine-ui`

**Comment by lihbr** [comment]
It appears `node-fetch` is now being used by `sm-commons` (https://github.com/prismicio/slice-machine/blob/master/packages/sm-commons/methods/communication.js#L1) without being declared as a dependency of said package: https://github.com/prismicio/slice-machine/blob/master/packages/sm-commons/package.json#L27-L36

I don't know if this code is still in use, if yes, the issue remains.

**Comment by mdeclercq** [comment]
Hi @lihbr,
This has been fixed in the release `1.0.0`. Feel free to re-open the issue if needed.
Thanks,
