### ISSUE TITLE
Nuxt srcDir conflict between nuxt-sm & prismic-cli

### ISSUE THREAD

**Issue by lihbr** [prismicio/slice-machine#22]
### Version

- Prismic CLI version (know it by running `prismic --version`): 3.8.0-beta.0 & previous

### Reproduction

1. `npx create-nuxt-app` (default preset is fine)
2. `prismic sm --setup`
3. add `slice-zone` component inside your page (if you stop here everything works fine)
4. add key `srcDir` to `nuxt.config.js` and set it to `src` (whatever), then move all folder inside it (except `node_modules` and `.nuxt` of course)

### What is expected?

`nuxt-sm` should handle `srcDir` option correctly.

### What is actually happening?

**Two cases:**

- If you don't move `sm.json` to new `src` folder you get this error when running Nuxt: `[Vue warn]: Error in render: "TypeError: Cannot read property 'resolver' of undefined"` because [`nuxt-sm` expect `sm.json` to be at `srcDir` level](https://github.com/prismicio/slice-machine/blob/master/packages/nuxt-sm/src/index.js#L49)

- If you move `sm.json` to `src` folder then Nuxt works well but `prismic sm --create-slice` fail:
  - At root level: SM file not found
  - Inside `src` folder: `Something (really) wrong happened. If the problem persists, feel free to contact us!
[Full error] Error: [Error] Please specify a framework by using "--framework <framework_name>"` because `sm.json` is not at the same level `package.json`, using the `--framework` flag doesn't help

### Any additionnal information
1. What does the `@` mean in `sm.json` libraries array? (`@/slices`) it's the path relative to this directory from `sm.json`?
2. `nuxt-sm` should expect `sm.json` to be at `Nuxt.options.rootDir` instead of `Nuxt.options.srcDir` by default ([`rootDir` has the same value as `srcDir` by default](https://nuxtjs.org/api/configuration-srcdir)), should be an easy fix if that's just that? Can you confirm scope @hypervillain?

**Comment by hypervillain** [comment]
Good catch, using `rootDir` should work fine here. Not sure we have to change anything for `--create-slice` though, as you could simply change the path to your slices folder.

@ (or ~) means that the path to your library is local. It's used by the CLI and `sm-commons` package.

**Comment by lihbr** [comment]
*Update `02/17/2021`:*
1. Still a bug

**Comment by hypervillain** [comment]
@lihbr I think we could treat @ prefix depending on the framework you use and take rootDir into consideration in this case: call create slice from root folder to get the package.json but identify rootDir and look for slices folder from there

**Comment by lihbr** [comment]
I don't think it was related to that but just to `nuxt-sm` not handling the `rootDir` options from Nuxt, ping me if you want to tackle it together!
