### ISSUE TITLE
importing SliceZone in Nuxt does not work (Cannot use import statement outside a module)

### ISSUE THREAD

**Issue by samuelhorn** [prismicio/slice-machine#226]
### Versions
- slice-machine-ui: 0.1.1
- node: 16.11.1

### Reproduction
Unfortunately this is only in local dev for now. But tell me if I could help in any way.

<details open>
<summary>Additional Details</summary>
<br>
Versions from package.json:
<pre>
...
  "dependencies": {
    "@nuxtjs/prismic": "^1.3.2",
    "@nuxtjs/sitemap": "^2.4.0",
    "@nuxtjs/svg": "^0.2.0",
    "@storybook/addon-actions": "^6.3.12",
    "core-js": "^3.15.1",
    "fuse.js": "^6.4.6",
    "gsap": "^3.8.0",
    "nuxt": "^2.15.8",
    "nuxt-sm": "^0.0.8",
    "v-click-outside": "^3.1.2",
    "vue-gtag": "^1.16.1",
    "vue-slicezone": "^0.1.0",
    "vueisotope": "^3.1.2"
  },
  "devDependencies": {
    "@nuxtjs/storybook": "3.3.1",
    "@nuxtjs/tailwindcss": "^4.2.0",
    "@storybook/vue": "6.1.21",
    "nuxt-webfontloader": "^1.1.0",
    "postcss": "^8.3.5",
    "slice-machine-ui": "^0.1.1"
  }
...
</pre>

From nuxt.config.js:
<pre>
...
build: {
  transpile: ["vue-slicezone", "nuxt-sm"]
},
...
</pre>

From pages/index.vue:
<pre>
...
<script>
import SliceZone from 'vue-slicezone'

export default {
  components: {
    SliceZone
  },
}
</script>
...
</pre>
</details>

### Steps to reproduce
Inside index.vue adding a script tag with:
```
<script>
  import SliceZone from 'vue-slicezone'

  export default {
    components: {
      SliceZone
    }
  }
</script>
```

### What is expected?
Being able to import slice-zone without any errors.

### What is actually happening?
Error thrown: Cannot use import statement outside a module

**Comment by octavioamu** [comment]
having this same error but with vue-essential-slices was you able to fix it @samuelhorn ?

**Comment by samuelhorn** [comment]
@octavioamu Sorry, I think it was some kind of error on my end, thats why I closed it. 
Removed the project and started from scratch solved it for me. 

I guess it was some kind of version missmatch somewhere.
