### ISSUE TITLE
Change default config for links and add UI for easy configuration

### ISSUE THREAD

**Issue by eveningforgery** [prismicio/slice-machine#251]
### Is your feature request related to a problem? Please describe.
When adding a new link, the generated json found in `model.json` is:
```json
"link": {
  "config": {
    "label": "link",
    "placeholder": "",
    "select": "web",
    "allowTargetBlank": false
  },
  "type": "Link"
}
```
This is quite annoying having to change manually the select property from `"web"` to `null` every time you want to leave the option to the end user to select whatever they want, internal, web or media, which is most of the time.

Currently, there is no way to change the configuration in the UI:
![Link edit UI](https://puu.sh/IudBA/91b9497823.png)

Moreover, when selecting the "Link" field, the current description says:

> A link to web, media or Prismic document

which is currently not the case

### Describe the solution you'd like

By default, the generated config for links should be more permissive, while still having the option to restrict it if needed in the UI.
```json
"link": {
  "config": {
    "label": "link",
    "placeholder": "",
    "select": null,
    "allowTargetBlank": true
  },
  "type": "Link"
}
```

Since there is already other types of links such as "Content Relationship" and "Link to media",
the addition of simple checkboxes would do the trick:
![UI Suggestion](https://puu.sh/IudLp/54f11638a1.png)

### Describe alternatives you've considered

An other alternative would be to split every type of link into a different field. Having now 4 fields for links:
- Link (being a new one with `select` set to `null`)
- Content Relationship
- Link to media
- Link to the Web (renaming the current slicemachine "Link")

**Comment by comeprismic** [comment]
Hi! 
I'm closing the issue since it has been solved since then, in latest version of Slice Machine. 
Thanks again for submitting it.
