### ISSUE TITLE
RFC: create CLI bootstrap command to start from a cloned slicemachine repository

### ISSUE THREAD

**Issue by arnaudlewis** [prismicio/slice-machine#28]
## Summary

We want to add a way to synchronize your components between Prismic and your project.
It would be a CLI command that will scan all your slices on Prismic side and all your slicemachine components on the other side to help you create the missing ones and update the others if needed.

We want to add a way to start right away from an existing slicemachine project.
Let's say that you created a slicemachine project with a prismic repository attached to it. If you want to clone this repository and start from there, you'll need to create a new prismic repository and generate the custom types from your code.
In this case, you just run `prismic sm --bootstrap` and it will find your custom types in the project, ask you to create a new prismic repository and insert the custom types in it.

## implementation

Have two commands:
  - `--setup`:
    - write the `sm.json` config file
    - install node dependencies
    - create files related to the framework and setting up
    - find all the slices inside the project from modules + local
    - build the initial custom types
    - write the custom types in the file system
    - call the bootstrap command

If the `sm.json` already exists, the setup command should stop and suggest to run the `bootstrap` command

  - `--bootstrap`
    - read the custom types from the file system
    - Create a prismic repository with the custom types

If the custom types don't exist in the filesystem, we suggest to run the `setup` command.

**Comment by arnaudlewis** [comment]
Implementation: https://github.com/prismicio/prismic-cli/pull/50

**Comment by lihbr** [comment]
> If the `sm.json` already exists, the setup command should stop and suggest to run the `bootstrap` command
> 
> * `--bootstrap`
>   
>   * read the custom types from the file system
>   * Create a prismic repository with the custom types

I get it, but if `sm.json` exists this mean that the Prismic repository already exists right? 🤔 Or I don't get the use case if that's more than a `push`~

**Comment by arnaudlewis** [comment]
It’s like a theme, yes a repo exists but you want to clone the project to provision a new website or a new environnement for instance. So you need to create a new repo and update the config

**Comment by lihbr** [comment]
Closing since implemented! 🎉
