### ISSUE TITLE
queryType="single" not working

### ISSUE THREAD

**Issue by levimykel** [prismicio/slice-machine#29]
### Version

- Prismic CLI version (know it by running `prismic --version`): 3.8.0-beta.0
- "vue-slicezone": "0.0.26"

### Reproduction
When I use `<slice-zone type="homepage" queryType="single" />` I get the default Slice Zone content 
<img width="300" alt="Screen Shot 2020-07-10 at 3 24 33 PM" src="https://user-images.githubusercontent.com/9385378/87159342-7a075900-c2c1-11ea-8bec-9290be487b7c.png">

### What is expected?
When I use the UID it works as expected and shows the content `<slice-zone type="homepage" uid="home" />`
I would expect that if I remove `uid="home"` and add `queryType="single"` that it would work as well.

### What is actually happening?
If I remove `uid="home"` then it doesn't work when I pass any value into queryType. It doesn't appear to run the query at all. I saw the same behavior (returning no results) when adding `<slice-zone type="homepage" queryType="multi" />`.

But if I add `uid="home"` and `queryType="single"` then it works: `<slice-zone type="homepage" uid="home" queryType="multi" />`.

So it appears that this issue is more tied to the `uid` prop being missing than adding the `queryType`.

### Any additional information
None

**Comment by hypervillain** [comment]
Hey @levimykel,

what's your project custom types at the moment? If you indeed created a single document type "homepage", your first bit of code should correctly retrieve it. Your last portion of code makes me think that homepage is actually a repeatable type. Happy to investigate anyway ✌️

**Comment by levimykel** [comment]
@hypervillain I've invited you to the repo. The homepage Custom Type is definitely a Single type. Also I don't think it should matter because `getSingle` will work for repeatable types and just return the first item in the response. So it seems that it should work in any case.

**Comment by levimykel** [comment]
@arnaudlewis

**Comment by hypervillain** [comment]
Fixed by #41 !
