### ISSUE TITLE
Vue SliceZone doesn't output the same markup depending on usage

### ISSUE THREAD

**Issue by lihbr** [prismicio/slice-machine#30]
### Version

- Prismic CLI version (know it by running `prismic --version`): 3.8.0-beta.0
- `vue-slicezone`: 0.0.26

### Reproduction

1. Use `slice-zone` component the internal query way: `<slice-zone type="page" uid="home" />`
2. Use `slice-zone` component the external query way: `<slice-zone :slices="data.body" />`

### What is expected?

- Markup structure should be the same
- HTML attribute `slices` should be output on external query way
- Markup structure should remain minimal: parent (`slice-zone` component) > children (`slices`), no additional wrappers are desired here.

### What is actually happening?

**Internal query way:**
- Output is wrapped an unnecessary amount of time, breaking usage of classes applying style to direct children ([like Tailwind CSS `space-between` utility](https://tailwindcss.com/docs/space))
![image](https://user-images.githubusercontent.com/25330882/87165882-09653a00-c2cb-11ea-970b-b160f13a68fd.png)
> Slices are overwrapped

**External query way:**
- `slices` is outputed as an HTML attribute which is undesired and not a valid HTML attribute
![image](https://user-images.githubusercontent.com/25330882/87165785-e8044e00-c2ca-11ea-8bcc-9d9f29941bd4.png)
> `slices` attribute is outputed

### Any additional information

None

**Comment by hypervillain** [comment]
I believe the only way we could get rid of that div atm, would be to transform `PageFetch` into a render function. I can look into it! Can you make a PR to remove the unnecessary HTML attributes?

**Comment by lihbr** [comment]
Indeed I think it'll make sense to refactor `PageFetch` into a render function displaying either the `SliceZone` or `Loading` component, working on a PR to fix those attributes.

**Comment by lihbr** [comment]
*Update `02/17/2021`:*
1. I resolved conflicts on my PR, checking it with @hypervillain soon!
