### ISSUE TITLE
`--add-storybook` command does not bootstrap a context aware configuration

### ISSUE THREAD

**Issue by lihbr** [prismicio/slice-machine#31]
### Version

- Prismic CLI version (know it by running `prismic --version`): 3.8.0-beta.0

### Reproduction

1. Bootstrap a Slice Machine project with Nuxt.js or Next.js then run `add-storybook`

### What is expected?

Not sure to what extent it's one of our goals but it'd be truly awesome if Slice Machine was able to output a right Storybook config depending on your libraries requirements.

### What is actually happening?

Slice Machine `--add-storybook` command just bootstrap a standard Storybook config, letting the user configure it on its own later on.

### Any additional information

Well as I said it's a tough one as we cannot guess libraries requirements easily or we can capture user intention with an interactive prompt while running the `--add-storybook command` but then we're still facing a lot of edge cases.

For Vue libraries basically:
- [`vue-essential-slices`](https://github.com/prismicio/vue-essential-slices) relies mainly on (links to Storybook configs):
  - [SASS](https://github.com/prismicio/vue-essential-slices/blob/master/.storybook/main.js#L22-L26)
  - [Alias resolving](https://github.com/prismicio/vue-essential-slices/blob/master/.storybook/main.js#L34-L37)
- [`sms-hoy`](https://github.com/lihbr/sms-hoy) relies on (links to Storybook configs):
  - [Tailwind CSS](https://github.com/lihbr/sms-hoy/blob/master/.storybook/main.js#L25-L43)
  - [Alias resolving](https://github.com/lihbr/sms-hoy/blob/master/.storybook/main.js#L50-L53)

And the list could go on with future libraries, what if someone makes a Slice Machine library based on Stylus? Vuetify? Bootstrap? Basically any dependencies of a library should be both handled by the framework using it and the Storybook documenting it.

An attempt at solving this issue could be leveraging functions like [`getWebpackConfig`](https://github.com/nuxt/nuxt.js/pull/5378) for Nuxt.js and similar for Next.js to attempt to merge it with Storybook's one in order for users to configure it only at one place, this will cover most cases but not all, [more about it here](https://dev.to/f3ltron/storybook-tailwind-nuxt-one-webpack-config-3kbj).

**Comment by Duaner** [comment]
Maybe it will be interesting to introduce an automated process on the CLI to fasten your automation like the one nuxtjs is offering at the creation of your project. 

Asking you which framework you're using. 
Like Saas
Tailwind? 

If we are recreating `npx -p @storybook/cli sb init --type` vue can we just run the command in the add storybook command when we do add storybook for the first launch? @hypervillain @lihbr 

Can we use the nuxt config to see that if they already configured it in their nuxt project ?

**Comment by lihbr** [comment]
In August Nuxt.js came up with an official Storybook module, providing users with a context aware configuration for Nuxt project out of the box, therefore simplifying our work for this framework.

@hypervillain and I will update the `--add-storybook` command to reflect those changes for Nuxt.js, closing part of this issue.

**Comment by lihbr** [comment]
prismicio/prismic-cli#62 has been merged in mm/meta-2020, closing~
