### ISSUE TITLE
Updating slices doesn't work via slice-machine-ui

### ISSUE THREAD

**Issue by Choem** [prismicio/slice-machine#311]
### Versions

- slice-machine-ui: v0.1.2
- node: v16.13.2 (LTS)
- macOS Monterey v12.0.1

### Reproduction
Locally

### Steps to reproduce
To reproduce follow [the tutorial](https://prismic.io/docs/technologies/nextjs) to setup a new project with NextJS and Prismic.
After this I have everything up and running locally. The NextJS app, the slicemachine and the storybook.

So I wanted to create my first component with the slice-machine-ui following [this tutorial](https://prismic.io/docs/technologies/create-and-model-a-component-nextjs).

After creating a slice for the first time the slice-machine-ui immediately threw an error in my terminal saying:
`[slice/save][Slice: TextImageRight][variation: default-slice]: Error: Node has 0 height.`. 

First I thought it threw an error regarding the height of the image, because I forgot to set it.
So I set the height and width to both 200px. Saved the component locally and got the error again in the terminal.

Also tried it without the image field but that didn't help either.

**Note that it does create the TextImageRight component initially but doesn't update on further field updates in both zones** 

### What is expected?
Updates the component locally in `~/slices/TextImageRight`

### What is actually happening?
```
Launching server...

[slice/save]: Updating slice model

[slice/save]: Generating mocks

[slice/save]: Generating stories

[slice/save]: Generating screenshots previews

[slice/save][Slice: TextImageRight][variation: default-slice]: Error: Node has 0 height.
[slice/save]: Slice was saved!

[slice/save]: Libraries index files regenerated!

[slice/save]: Updating slice model

[slice/save]: Generating mocks

[slice/save]: Generating stories

[slice/save]: Generating screenshots previews

[slice-machine] (node:47767) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use node --trace-deprecation ... to show where the warning was created)

[slice/save][Slice: TextImageRight][variation: default-slice]: Error: Node has 0 height.

[slice/save]: Slice was saved!

[slice/save]: Libraries index files regenerated!
```

**Comment by Choem** [comment]
When _downgrading_ my slice-machine-ui from v0.1.2 to v0.1.1 in the package.json it works again without any errors showing in the terminal. Logs:
```
[slice/save]: Updating slice model

[slice/save]: Generating mocks

[slice/save]: Generating stories

[slice/save]: Generating screenshots previews

[slice-machine] (node:50200) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)

[slice/save]: Slice was saved!

[slice/save]: Libraries index files regenerated!

[slice/push]: uploading variation preview

[slice/push]: pushing slice model to Prismic

[slice/push] done!
```

But the slice in `~/slices/TextImageRight` still contains the old fields. Shouldn't these be updated as well?

**Comment by phillysnow** [comment]
Hi Choem,

Sorry we never got back to you on this one, it has since been fixed in newer versions. Please try a fresh install if you are seeing the issue in your project.

Thanks.
