### ISSUE TITLE
Vue: Prismic preview doesn't work with partials (nav, header, footer, etc.)

### ISSUE THREAD

**Issue by lihbr** [prismicio/slice-machine#33]
### Version

- Prismic CLI version (know it by running `prismic --version`): 3.8.0-beta.0
- `vue-slicezone`: 0.0.26

### Reproduction

1. Create a "menu" singleton type on Prismic and fill it with menu items
2. Use one of the following methods to fetch those menu items:
    - [Page Middleware](https://nuxtjs.org/api/pages-middleware) ([it's recommended way](https://www.slicemachine.dev/documentation/nav-bars-and-menus))
    - [Nuxt fetch hook](https://nuxtjs.org/api/pages-fetch)
    - [nuxtServerInit store hook](https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action)
3. Display those links inside a menu component and use this menu component inside `layouts/default.vue`
4. Try to use the preview feature on "menu" singleton

### What is expected?

Preview should be working.

### What is actually happening?

Preview works only for the page content.

### Any additional information

This is not an issue on our side in the sense that it's not implemented yet/we didn't find a proper way around that one yet. I don't get why the `fetch` hook works on SliceZone (https://github.com/prismicio/slice-machine/blob/master/packages/vue-slicezone/PageFetch.vue#L77-L88) but not on other components though 🤔 Any idea on that one @hypervillain?

**Comment by lihbr** [comment]
Perhaps we should try to leverage the new [`enablePreview` function](https://nuxtjs.org/blog/going-full-static#preview-mode) at Nuxt module level to work that around? Made a Nuxt plugin like that for my website already: 
```javascript
import { parse } from "cookie";
import Vue from "vue";

export default context => {
  /**
   * Check if request has a preview token
   * @return {Boolean} - true if a preview token is found
   */
  const hasToken = () => {
    if (typeof document === "undefined") {
      return false;
    }

    const prismicCookie = parse(document.cookie)["io.prismic.preview"];

    if (!prismicCookie) {
      return false;
    }

    try {
      return !!JSON.parse(prismicCookie)[
        `${process.env.PRISMIC_REPO}.prismic.io`
      ].preview;
    } catch (err) {
      if (context.app && context.app.$logger) {
        context.app.$logger.error(err);
      } else {
        console.error(err);
      }
      return false;
    }
  };

  const preview = {
    hasToken
  };

  Vue.prototype.$prismicPreview = preview;
  context.$prismicPreview = preview;

  // Enable preview if needed
  if (hasToken()) {
    context.enablePreview();
  }
};
```

**Comment by hypervillain** [comment]
That would work for people leveraging the new full static mode (and we should implement it for them) but we should find something for others too

**Comment by lihbr** [comment]
*Update `02/17/2021`:*
1. I think that still a bug, need to try to reproduce

**Comment by kb1995** [comment]
This is also a problem for me at the moment for my Next.js website. Any updates around this? @lihbr @hypervillain

**Comment by lihbr** [comment]
Confirmed bug on Nuxt end, related PR: https://github.com/nuxt/nuxt.js/pull/9530

Status: likely won't be merged, Nuxt effort is moving to Nuxt 3, therefore closing this issue.
