### ISSUE TITLE
Removed `getStoriesPaths` in slice-machine-ui 0.2.0

### ISSUE THREAD

**Issue by EddyVinck** [prismicio/slice-machine#338]
### Versions

- @prismicio/client: ^6.0.0,
- @prismicio/helpers: ^2.0.0,
- @prismicio/react: ^2.0.3
- next: 12.0.3
- slice-machine-ui: 0.2.0
- node: 16.13.0

### Reproduction

Update to slice-machine-ui 0.2.0 on an existing project

### What is expected?

`getStoriesPaths` should be available 

```
const { getStoriesPaths } = require("slice-machine-ui");
```

The documentation still has this line: https://prismic.io/docs/technologies/storybook-nextjs#update-the-main.js-file

![image](https://user-images.githubusercontent.com/23434753/152133165-61cd9c49-780e-47e8-8ee7-7b61d0df1142.png)

I can of course stay on slice-machine-ui  0.1.2 until this can be resolved, but it would be nice to be able to upgrade.

### What is actually happening?

This export `getStoriesPaths` was removed or changed in 0.2.0 and I can't find it.

### Question about slice simulator

https://prismic.io/docs/technologies/setup-slice-simulator-nextjs

I just read about this. Is it new and is it the preferred solution for slice-machine screenshots of slices in the future?

**Comment by EddyVinck** [comment]
Last night I managed to upgrade to Slicemachine 0.2.0 with the [slice simulator](https://prismic.io/docs/technologies/setup-slice-simulator-nextjs).

I wish we didn't have to install `next-slicezone` and `prismic-reactjs` to use the slice simulator since these are old packages, but anyway I copied the `getStoriesPaths` from the `slice-machine-ui@0.1.2` source so I could keep using storybook.

```js
const glob = require("glob");
const getStoriesPaths = () => {
  return [
    ".slicemachine/assets/**/*.stories.@(js|jsx|ts|tsx|svelte)",
    "customtypes/**/*.stories.@(js|jsx|ts|tsx|svelte)",
  ].reduce((acc, p) => (glob.sync(p).length ? [...acc, `../${p}`] : acc), []);
};
```

Somewhat unrelated, but I also added the following to my `pages/slice-simulator.tsx` so that page doesn't get shipped to production. (See the [notFound NextJS documentation](https://nextjs.org/blog/next-10#notfound-support))

```js
export function getStaticProps() {
  if (process.env.NODE_ENV === "production") {
    return { notFound: true };
  }
  return { props: {} };
}
```

**Comment by IsaiahByDayah** [comment]
Thanks for this! Will update so I can continue using Storybook.

Being already set up (and liking) Storybook, have you found any benefit to the new Slice Simulator?

**Comment by Miniplop** [comment]
Hello @EddyVinck, thank you for reporting this.

We put back the function in the version 0.3.0 : https://github.com/prismicio/slice-machine/pull/387.

Also as we want to focus the slice machine ui package on being a local app and not becoming a toolbox, we flagged this function as deprecated. 

This function will be removed on futur releases. For the moment we don't where this function will be, probably into a helper package or into a storybook plugin for the SM. 

See you soon

**Comment by EddyVinck** [comment]
Thanks @Miniplop 🎉
