### ISSUE TITLE
Overwrote a slice without a warning

### ISSUE THREAD

**Issue by danielphilipjohnson** [prismicio/slice-machine#341]
### Versions

- slice-machine-ui: 0.2.0
- node: 14.17.2
- nuxt: 2.15.8,
- nuxt-sm: 0.1.0"

### Reproduction
Create a slice with the same name

### Steps to reproduce

Create a slice called MySlice and add some fields. Then create the same slice again.

### What is expected?
To receive some warning that I'm about to overwrite my changes or do I want to continue.

### What is actually happening?

I was working on a big project with a lot of slices and didn't realise I had reused a similar name. I was unaware I overwrote a slice that was used in various documents.

**Comment by comeprismic** [comment]
Hi! Thanks for reaching out! We are aware of this issue and we will come up with a fix in the coming releases. We'll keep you up to date.

**Comment by chamois-d-or** [comment]
Hey there,
Sorry for the lack of communication, this issue has been fixed since then.
