### ISSUE TITLE
No option in —setup —lib for no libs

### ISSUE THREAD

**Issue by justinmetros** [prismicio/slice-machine#35]
Have existing Vue projects and don't want vue-essential-slices or any other, just the tool.

Is it possible to install with no framework, just slicemachine?

**Comment by lihbr** [comment]
Hi @justinmetros and thanks for contributing!

Currently there's no straightforward way to do that, what I'd recommend you is to run the `--setup` command with the `--no-prismic` flag, then you can safely remove `vue-essential-slices` (as well as `node-sass` and `sass-loader` if you're not using those) from your dependencies, finally you'll need to remove `vue-essential-slices` from the `libraries` array inside your `sm.json` config file and then you should be good to go 🙂 

Also we were discussing the `--no-lib` option here: https://github.com/prismicio/slice-machine/issues/25#issuecomment-651895322 ~

**Comment by justinmetros** [comment]
Thank you @lihbr, very clear and easy enough.
