### ISSUE TITLE
Please only show the new version modal when starting slicemachine

### ISSUE THREAD

**Issue by EddyVinck** [prismicio/slice-machine#353]
### Is your feature request related to a problem? Please describe.

When I'm not ready to update Slicemachine at any moment there is an update available, I get shown the modal when I'm running my Slicemachine UI locally every time I change pages.

### Describe the solution you'd like

Only show the update modal when starting the Slicemachine UI locally. Do not show it every time /api/state is called.

### Describe alternatives you've considered

I temporarily changed my `node_modules/slice-machine-ui/build/lib/env/semver.js` function `createComparator` to always return the `DefaultComparison`, but I'd rather not mess around in my `node_modules`

**Comment by MarcMcIntosh** [comment]
Should be fixed in v0.2.1 :)

**Comment by EddyVinck** [comment]
Yeah I noticed, closing this now @MarcMcIntosh 

For reference: https://github.com/prismicio/slice-machine/releases/tag/slice-machine-ui%400.2.1 

> The update modal that was popping up too often was removed.
