### ISSUE TITLE
Nuxt sm doesn't support server side rendering

### ISSUE THREAD

**Issue by Xayer** [prismicio/slice-machine#38]
### Version

- Prismic CLI version (know it by running `prismic --version`): 

### What is expected?

Nuxt sm should fetch the slices from prismic using AsyncData, and allow the site to server side rendered, so that applications using slice machine can be statically generated. 

### What is actually happening?

When using Nuxt sm,it is using vue slicezone. Vue slice zone fetches the content for the page, meaning it will fetch the slice machine content after the page has loaded, and not during async Data.That means that the content gets fetched "too late" for Nuxt to be able to cache it during `generate`.

**Comment by lihbr** [comment]
Hey @Xayer thanks for your contribution!

What version of Nuxt.js are you using? Everything should be good if you're using `2.12` or greater with [`fetch` hook rework](https://nuxtjs.org/guides/features/data-fetching#the-fetch-hook).

`vue-slicezone` actually use this hook [internally](https://github.com/prismicio/slice-machine/blob/master/packages/vue-slicezone/PageFetch.vue#L77-L88) to fetch your documents which should allow your website to be statically generated.

Here's an example of a Slice Machine website on Netlify running Nuxt.js 2.14.1: https://sms-hoy.netlify.app If you get to the network tab on the devtool you'll see that the only XHR call made is just for initing Prismic API, no data get actually transferred.

Let me know if you're indeed experiencing the issue! If so please provide further information so I can attempt to reproduce the issue 🙂

**Comment by Xayer** [comment]
Alright, I was clearly wrong. I just had this thought that it might have been the case for some odd reason.
I wasn't near a computer to be able to check it it exactly.
I thank you very much for your help.
~~Does that mean that if we want to use the $prismic from the context, we should use it on the fetch method?~~
Edit: Yes, yes it was the way to do it :D Thanks alot!
