### ISSUE TITLE
Disable index file generation in manifest

### ISSUE THREAD

**Issue by itsjoekent** [prismicio/slice-machine#396]
### Is your feature request related to a problem? Please describe.

Slice Machine autogenerates and outputs an index file that doesn't conform to our application requirements.

### Describe the solution you'd like

It would be great if we could write `outputIndex: false` in our `sm.json` manifest file and disable the auto-generation of the `index.ts` file.

**Comment by phillysnow** [comment]
Hi Joe,

Can you tell us more about the standards you expect in your index file?

**Comment by itsjoekent** [comment]
@phillysnow I'd love to be able to code split, or support different import types (default vs named).

**Comment by lihbr** [comment]
Slice Machine should not be generating this file anymore 👌
