### ISSUE TITLE
`slice-machine-ui v0.2.1` does not support/removes slice zone labels from custom types

### ISSUE THREAD

**Issue by pentatiby** [prismicio/slice-machine#397]
### Versions

- slice-machine-ui: `v0.2.1`
- node: `v14.19.0`

### Steps to reproduce
- run the same versions as above
- create a new custom type folder, I called mine `testtype`
- paste [the JSON from this test](https://github.com/prismicio/slice-machine/blob/v0.2.1/packages/slice-machine/tests/project/customtypes/withslicezones/index.json) in `index.json` for this new custom type
- open `http://localhost:9999/cts/testtype` (or your custom url for this custom type)
- add a dummy `uid` field and hit 'Save to File System'
### What is expected?
I expect the new field to be added and the json to be otherwise structurally the same
### What is actually happening?

<details open>
<summary>
The JSON is stripped of `labels` fields under slice zones. Here is the resulting diff, after the above steps (the code is formatted with prettifier)
</summary>

```diff
diff --git a/src/customtypes/testtype/index.json b/src/customtypes/testtype/index.json
index b9fa52b0a..3386f3166 100644
--- a/src/customtypes/testtype/index.json
+++ b/src/customtypes/testtype/index.json
@@ -1,14 +1,21 @@
 {
-  "id": "withslicezones",
+  "id": "testtype",
   "label": "WithSliceZones",
   "repeatable": false,
+  "status": false,
   "json": {
     "Main": {
+      "uid": {
+        "config": {
+          "label": "uid",
+          "placeholder": ""
+        },
+        "type": "UID"
+      },
       "MainSliceZone": {
         "type": "Slices",
-        "fieldset": "Slice zone",
+        "fieldset": "Slice Zone",
         "config": {
-          "labels": {},
           "choices": {
             "alternate_grid": {
               "type": "Slice",
@@ -89,9 +96,8 @@
     "Tab2": {
       "ASliceZone": {
         "type": "Slices",
-        "fieldset": "Slice zone",
+        "fieldset": "Slice Zone",
         "config": {
-          "labels": {},
           "choices": {
             "cards_carousel": {
               "type": "Slice",
@@ -166,6 +172,5 @@
         }
       }
     }
-  },
-  "status": false
+  }
 }
```
</details>

**Comment by phillysnow** [comment]
Hey @pentatiby,

Slice Labels are not supported in Slice Machine and have been replaced by Slice Variations. You can add a variation in the Slice Machine UI, it serves the same purpose with much more power.

We discuss. use cases for variations and best practices here:
https://community.prismic.io/t/recommended-use-cases-for-slice-variations/8809

Reach out to us on the forum for fast responses from our team.

Thanks.
