### ISSUE TITLE
faker as a dependency

### ISSUE THREAD

**Issue by jasonmit** [prismicio/slice-machine#402]
Based on a quick grep of the codebase, `faker` is only used as a `devDependency` but is marked as a [`dependency`](https://github.com/prismicio/slice-machine/blob/453613bba838389299c607763e12db8344bf06f7/packages/slice-machine/package.json#L64) which means consumers of `slice-machine-ui` end up installing faker as part of their yarn / npm install (which is a sizable project).

If it is used, would you be open to migrating to `@faker-js/faker` to avoid double installs for projects that have migrated over?

If my assumptions are correct, I'll send over a quick PR to address.

Thank you

**Comment by Miniplop** [comment]
Hello thank you for reporting this, 

We will make a complete checkup of the SM dependencies on the release 0.3.4 to 1) Avoid installing extra dependencies 2) remove some unused dependencies. 

I will keep you update

**Comment by webda2l** [comment]
@Miniplop Yes fixing the deps vunerabilities asap will be welcome. The high one, at least.

![image](https://user-images.githubusercontent.com/517753/163984719-0e8a8b85-68d1-4d5a-bf1b-7885644d89a3.png)

**Comment by Heyrows** [comment]
Hey @jasonmit  thanks for reporting this issue 😄.
This has been fixed in the latest Slice Machine versions so i'll close this issue. 🎉
