### ISSUE TITLE
SliceLike missing type declarations

### ISSUE THREAD

**Issue by itzaks** [prismicio/slice-machine#417]
### Versions

- "@prismicio/vue": "^3.0.0-beta.5"
- "@nuxtjs/prismic": "^3.0.0-alpha.1"
- "@prismicio/slice-simulator-vue3": "^0.1.0"
- "@prismicio/types": "^0.1.27"

### The issue
When creating a vue-template in my Nuxt 3 project and trying to add a slice, I run in to some missing typescript declarations in my template.

`Property 'primary' does not exist on type 'SliceLike<string>'.ts(2339)`

Template and setup is defined like this:

```html
<template>
<h3>{{ slice.primary.title }}</h3> 
</template>
```

```ts
<script lang="ts" setup>
import { getSliceComponentProps } from "@prismicio/vue";
defineProps(getSliceComponentProps(["slice", "index", "slices", "context"]))
</script>
```

**Comment by lihbr** [comment]
Hey there, I'm really sorry for the ridiculous delay it took for us to get back to you. Looks like this very valid issue fell under our radar...

Thank you so much for opening it! I just published a fix on our Vue kit (`3.1.1`), updating it should get things rolling as expected when not providing a type generic :)
