### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by itzaks** [prismicio/slice-machine#420]
### Versions

````
- slice-machine-ui: 0.3.3
- @nuxtjs/prismic: "alpha",
````

### Reproduction

Add both dependencies as devDependencies and run `npm/yarn run slicemachine`, will yield the following error:

````
/node_modules/@slicemachine/core/build/src/utils/cliLogs.js:8
const ora_1 = __importDefault(require("ora"));
                              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/ora/index.js 
from /node_modules/@slicemachine/core/build/src/utils/cliLogs.js not supported.
Instead change the require of index.js in /node_modules/@slicemachine/core/build/src/utils/cliLogs.js 
to a dynamic import() which is available in all CommonJS modules.
````

### Proposed solution

Use `import` instead of `require`.

**Comment by itzaks** [comment]
Seems like the problem isn't in the actual cliLogs-file, but rather that `esModuleInterop` is transforming the imports into requires.

**Comment by itzaks** [comment]
This seems to be an issue with slice machine rather than to have anything to do with @nuxtjs/prismic. It happens on a fresh project even without Nuxt installed. Just running:

````sh
yarn init
yarn dlx @slicemachine/init
yarn run slicemachine
````

Yields the error above. 

````
Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/ora/index.js from .../node_modules/@slicemachine/core/build/src/utils/cliLogs.js not supported.
````

Using the following:

````
yarn – 3.2.0
node – 16.14.0
slice-machine-ui – 0.3.3
````

I tried with npm 8.3.1 as well with no better luck.

**Comment by Crevitus** [comment]
This is happening for me as well on a fresh project with NextJs.

```
yarn – 3.2.0
node – 16.14.0
slice-machine-ui – 0.3.3
```

**Comment by Christopotamus** [comment]
Just had this issue and it turns out I had added node-fetch during a previous attempt to get something else working. Removing node-fetch fixed this issue for me, so it may be worth looking into other packages you may have installed. Other than having installed node-fetch, my project was a fresh next.js + prismic setup.

**Comment by jeremytenjo** [comment]
Current dirty solution is to install `node-fetch` v2.6.1 - `npm i node-fetch@2.6.1`

**Comment by Brewd3v** [comment]
++

**Comment by drewhayes** [comment]
I was having the same issue. The solution from @jeremytenjo  to install v2.6.1 worked for me.

(Using a next.js project--so the error isn't nuxt specific)

**Comment by mdeclercq** [comment]
Hi,

I'm closing the issue as this has been fixed. Let us know in case you encounter the issue again.

Thanks,
