### ISSUE TITLE
Include repeat setting for group field

### ISSUE THREAD

**Issue by gijsbotje** [prismicio/slice-machine#438]
### Is your feature request related to a problem? Please describe.

I found the config settings for group fields which makes it non-repeatable here https://prismic.io/docs/core-concepts/group#json-model. Unfortunately this config settings isn't available as an option within slicemachine. When you add it manually, it will also override on the next save of the custom type within slicemachine.

### Describe the solution you'd like

It would be great if this option could be added into the settings of the group field with a checkbox.

**Comment by hypervillain** [comment]
We're getting rid of the mock config in profit of a Form where you are able to create as many items as you want. It's accessible since 0.7.1 on the Simulator page
