### ISSUE TITLE
'npx @slicemachine/init' does not work

### ISSUE THREAD

**Issue by jose-uilton-ferreira** [prismicio/slice-machine#459]
in Next.js setup guide 

when i run the following command:
```bash
npx @slicemachine/init
```
The following is returned
```bash
init: required argument missing.
```

i am using linux mint

**Comment by Heyrows** [comment]
Hey @jose-uilton-ferreira.

The error
```
init: required argument missing.
```
seems weird as our Init script doesn't require arguments by default.

Could you give us more information about the different commands you tried before that ?
Is the issue still happening ?
Thanks 🙏

**Comment by jeanpierrecarvalho** [comment]
@jose-uilton-ferreira @Heyrows Upgrade your NPM version to the latest and the problem it's solved.

**Comment by roux1max** [comment]
Had the same issue as @jose-uilton-ferreira and upgraded NPM to the latest version.

It worked!

But shouldn't something like "minimum NPM version required" documented somewhere?

**Comment by StitiFatah** [comment]
> Had the same issue as @jose-uilton-ferreira and upgraded NPM to the latest version.
> 
> It worked!
> 
> But shouldn't something like "minimum NPM version required" documented somewhere?

Definitely, was using 14.x via nvm to fit another project's requirements and run into the issue

**Comment by angeloashmore** [comment]
Confirmed `@slicemachine/init` works on Node 14 and npm 6.

## Proposed solution

Update the minimum supported version of Node from 12 to 14. Node 12 is no longer maintained. Node 14 is under maintenance until 2023-04-30 ([see here](https://github.com/nodejs/release#release-schedule)).

See PR: #602

**Comment by mdeclercq** [comment]
Closing this issue. Since the version `0.5.1` of SliceMachine, the minimum supported Node version is set to 14 (still maintained).
