### ISSUE TITLE
Created slice has props declaration which gives warnings in eslint

### ISSUE THREAD

**Issue by timbenniks** [prismicio/slice-machine#46]
### Version

- Prismic CLI version (know it by running `prismic --version`): 3.7.0

### Reproduction

* Run `$ prismic sm --create-slice` and finish the setup.

### What is expected?

The prop "slice" should be added like this:

```js
props: {
  slice: { type: Object, required: true },
}
```

### What is actually happening?

The prop is added like this:
```js
props: ['slice']
```

### Any additional information
With default eslint or prettier settings in Nuxt a props should have a type. Without it is shows a warning.

**Comment by hypervillain** [comment]
Thanks for reporting this, Tim
https://github.com/prismicio/prismic-cli/pull/59

**Comment by lihbr** [comment]
Has been fixed, closing 🥳
