### ISSUE TITLE
Push all custom types at once

### ISSUE THREAD

**Issue by kb1995** [prismicio/slice-machine#460]
Hey there,

Currently if I clone a new repo with already existing custom types inside it, I need to go through every single custom type and push it to Prismic. It would be great if:

1. There is a button to push everything to Prismic at once
2. That's done automatically when bootstrapping a fresh repo.

**Comment by austinlangdon** [comment]
Our agency also needs this feature :-)

**Comment by hypervillain** [comment]
Implemented in 0.7.1
