### ISSUE TITLE
'npx @slicemachine/init' does not work (caused by trackers!)

### ISSUE THREAD

**Issue by grumpyoldman-io** [prismicio/slice-machine#466]
## Please dont take this as me being ungrateful, the tool is helpful, but tracking people without consent is illegal in the EU.

When running `npx @slicemachine/init`, there is a post request to https://api.segment.io/v1/batch. This is not very ethical to do without consent (not sure if it is even legal in the EU), and it actually breaks the install when segment.io is blocked on a network (like with a piHole).

The request contains my IP, node versions, anonymized username.

<details closed>
<summary>request body</summary>
<br>
{"batch":[{"event":"SliceMachine Init Start","anonymousId":"REDACTED","properties":{},"type":"track","context":{"library":{"name":"analytics-node","version":"6.0.0"}},"_metadata":{"nodeVersion":"REDACTED"},"timestamp":"REDACTED","messageId":"node-REDACTED"}],"timestamp":"REDACTED","sentAt":"REDACTED"}
</details>

### Reproduction

Block traffic to https://api.segment.io by routing it to local machine ip
run `npx @slicemachine/init`
see the installer throw out a request error:

```
<ref *1> Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 443,
  config: {
    url: 'https://api.segment.io/v1/batch',
    ... etc
```

### What is expected?

That tracking my behavior is done with consent, and not crashing the installer.

### Workaround

Add `--tracking false` flag to the script.

**Comment by comeprismic** [comment]
Hello Marvin,
Thanks for reaching out, and sorry about our late answer. 
We have just forwarded your message to our legal team that will reach out to you by email about our terms of use. 
Regarding the tracking, you can indeed remove it by :

1. running the `npx @slicemachine/init` script and adding the flag `--tracking false`
2. or if you have already installed Slice Machine, adding the property `tracking` with value `false` in you `sm.json` file.

Best, 

Côme, Product @Prismic.

**Comment by grumpyoldman-io** [comment]
Heya @comeprismic, I did receive an email form someone in your legal team, and they told me there might be some changes being made in the future to be more transparent about tracking (again, I understand the need for metrics) which to me feels like the best solution. Thank you for responding and taking the extra step here. Keep up the good work. I'll close the issue for now as there is a fix.
