### ISSUE TITLE
TypeError: r.tabs.map is not a function

### ISSUE THREAD

**Issue by slaetthult** [prismicio/slice-machine#469]
I'm getting this error lately: TypeError: r.tabs.map is not a function.
I'm not able to edit Slices anymore.
![Bildschirmfoto 2022-05-18 um 13 55 58](https://user-images.githubusercontent.com/22275417/169033140-49b999aa-35a8-4fd3-b4fc-55dad6090b9d.png)

**Comment by danielphilipjohnson** [comment]
What Versions were you using?

- slice-machine-ui: 
- node: 

is it still happening or did you manage to solve it?

**Comment by lihbr** [comment]
Hey there,

Looks like this issue is still lacking context. If any display error is still happening please let us know, in the meantime, I'll close this issue.

💐
