### ISSUE TITLE
essential-slices components don't transpile with NextJS setup

### ISSUE THREAD

**Issue by jakeFeldman** [prismicio/slice-machine#49]
### Version

- `3.8.0-beta.1`

### Reproduction

Following the [Quick Start Guide](https://www.slicemachine.dev/documentation/next/nextjs-quick-start)

### What is expected?

SliceMachine components to load.

### What is actually happening?

Application is not able to transpile components from `essential-slices` pkg

![image](https://user-images.githubusercontent.com/25087876/95002506-0e681b80-0592-11eb-8f26-b949ffcee0c3.png)

### Any additional information

Seems like the `next-transpile-modules` pkg is not working. I tried various versions of nextjs to see if there was a compatibility issue between the two libs but each test ended with the same results.

**Comment by hypervillain** [comment]
I created a PR that adds `essential-slices` to the list of transpiled modules here: https://github.com/prismicio/slice-machine/pull/47 and it seemed to fix the loader issue. Can you confirm that applying the fix doesn't work on your side?

**Comment by jakeFeldman** [comment]
@hypervillain Thanks for the quick reply! I'll give this a try and get back to you ASAP!

**Comment by jakeFeldman** [comment]
@hypervillain Adding 'essential-slices' to the list of pkgs to transpile inside the `next.config.js` resolved the issue. Thank you for the help with this! Looking forward to trying out slice machine!

**Comment by lihbr** [comment]
PR Merged, closing. Thanks for your input Jake!
