### ISSUE TITLE
Can't resolve 'essential-slicessrcslices' on Windows

### ISSUE THREAD

**Issue by gowrizrh** [prismicio/slice-machine#51]
### Version

**- Prismic CLI version:** 3.8.0-beta.1

### Reproduction

Following the steps from,
https://www.slicemachine.dev/documentation/next/nextjs-quick-start

1. npx create-next-app my-new-app && cd my-new-app
2. prismic sm --setup
3. Add the `[uid].js` file 
4. Create a page type in prismic dashboard. example uid: test
5. Go to `localhost:3000/test` in a browser

### What is expected?

The page with the slices that were added in Prismic Dashboard

### What is actually happening?

![image](https://user-images.githubusercontent.com/40108018/96417761-48474c00-1239-11eb-8197-a49b43c8f598.png)

### Any additionnal information

Looks like a linter/formatter is automatically formatting the path?

I tried changing the first line in `sm-resolver.js` 
from `import * as EssentialSlices from 'essential-slices\src\slices'`
to `import * as EssentialSlices from 'essential-slices\\src\\slices'`

But, as soon as it compiles, it auto formats and reverts it to `import * as EssentialSlices from 'essential-slices\src\slices'`

Eventually leading to the said issue on Windows.

Works fine on macOS and Linux.

**Comment by lihbr** [comment]
Hey @gowrizrh, thanks for your contribution! I let know the product team about it, we should have a look at it soon!

**Comment by hypervillain** [comment]
Yes, expect a fix next week. In the meantime, you can simply rename this file to your convenience and import it in your page

**Comment by lihbr** [comment]
This has been fixed! 🥳
