### ISSUE TITLE
auto login problem

### ISSUE THREAD

**Issue by ghost** [prismicio/slice-machine#528]
Hi, 
I have a problem with prismic login.
When I run: $ npx @slicemachine/init

>> Press any key to open the browser to login or q to exit:
Opening browser to https://prismic.io/dashboard/cli/login?source=slice-machine
✔ Logged in as ***@gmail.com

looks all good, but it is waiting for 1-2 minutes in terminal and get an error:
Error! We failed to log you into your Prismic account

I tried 2 different account, but it has a same issue.

What can I do?

**Comment by pavery007** [comment]
@rezsodubiczki Hello, I am Patrick from Prismic. 
Have you been able to verify your login via the Prismic dashboard ([https://prismic.io/dashboard/login](https://prismic.io/dashboard/login)) and access your repos? What version of Slice Machine are you running?
Please let us know if the issue is still blocking you.

**Comment by ghost** [comment]
Hi @pavery007,
Dashboard login working fine, have an access for repos.
Problem is coming when I run: $ npx @slicemachine/init
I try to install slicemachine.

**Comment by hectorgabucio** [comment]
It happened to me too. I solved going to the dashboard link, I tell a bit about myself (name, job...) and after doing that, I tried the command again and it worked.

**Comment by Charlene-Bx** [comment]
I've fixed that issue by removing the .prismic file at the root with the command rm `~/.prismic`

**Comment by comeprismic** [comment]
Hi @rezsodubiczki did you manage to solve your issue by trying one of the proposed solutions?

**Comment by lihbr** [comment]
Closing as stale, feel free to reopen if you want to continue troubleshooting this one!
