### ISSUE TITLE
Greenfield create-next-app with @slicemachine/init does not create new slice libraries

### ISSUE THREAD

**Issue by frankstallone** [prismicio/slice-machine#541]
Running into some crazy bugs here. #540 was created earlier and this is another odd bug I am experiencing. 

### Versions

```
"dependencies": {
    "@prismicio/client": "^6.6.3",
    "@prismicio/helpers": "^2.3.2",
    "@prismicio/react": "^2.4.3",
    "@prismicio/slice-simulator-react": "^0.2.2",
    "next": "12.2.3",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "eslint": "8.20.0",
    "eslint-config-next": "12.2.3",
    "slice-machine-ui": "^0.4.1"
  }
```

```
node v16.15.1
npm v8.11.0
```

### Reproduction

1. Create new Next.js app `npx create-next-app [unique name here] --use-npm`
2. Run `npx @slicemachine/init`and follow the prompts to complete
3. Perform fixes in #540 for setting up a new project
4. Add `"@/blog"` to `sm.json` under `libraries` below `@.slices` [as described in the docs for adding a new slice library](https://prismic.io/docs/core-concepts/slice-machine#slice-libraries)
5. Run `npm run dev` and `npm run slicemachine`

### What is expected?

I would expect to create a new slice and under Target Library I would see `blog`. 

### What is actually happening?

I see no options in the drop menu. `slice` is the default, it's the only one that shows. Rebooting the servers changes nothing.

**Comment by phillysnow** [comment]
Hi @frankstallone,

This is actually an issue in the documentation, I've sent an docs update to get published.

So to add another collection of Slices to your project: 

1. Add a new folder in your project directory.
2. Open the sm.json file in your project, then add or modify the path to the new folder inside libraries. For example:

**Comment by frankstallone** [comment]
@phillysnow thanks for your response. Did you mean to have an example after you last statement above, "For example:"?

**Comment by phillysnow** [comment]
Ahh my bad

```
{
  "apiEndpoint": "https://your-repo-name.cdn.prismic.io/api/v2",
  "libraries": [
    "@/slices",
    "@/my-second-slice-lib"
  ],
  "_latest": "0.1.0",
  "localSliceSimURL": "http://localhost:3000/_simulator"
}
```
