### ISSUE TITLE
Greenfield create-next-app with @slicemachine/init Unable to generate screenshot for this page:

### ISSUE THREAD

**Issue by frankstallone** [prismicio/slice-machine#542]
Hot on the heels of #541 — this one is minor. Thinking I am doing something terrible wrong here somehow. 

### Versions

```
"dependencies": {
    "@prismicio/client": "^6.6.3",
    "@prismicio/helpers": "^2.3.2",
    "@prismicio/react": "^2.4.3",
    "@prismicio/slice-simulator-react": "^0.2.2",
    "next": "12.2.3",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "eslint": "8.20.0",
    "eslint-config-next": "12.2.3",
    "slice-machine-ui": "^0.4.1"
  }
```

```
node v16.15.1
npm v8.11.0
```

### Reproduction

1. Create new Next.js app `npx create-next-app [unique name here] --use-npm`
2. Run `npx @slicemachine/init`and follow the prompts to complete
3. Perform fixes in #540 for setting up a new project
5. Run `npm run dev` and `npm run slicemachine`
6. Go to `localhost:9999`
7. Click on Slices
8. Create a Slice
9. Name slice and click Create

### What is expected?

A screenshot preview to generate

### What is actually happening?

Server error: `[slice/save][Slice: NewAwesome][variation: default]: Unable to generate screenshot for this page: http://localhost:3000/slice-simulator?lid=slices&sid=new_awesome&vid=default`

**Comment by ReeceM** [comment]
This is an intermittent issue for me on my end where it says it can't create a screenshot. But then after a browser refresh on SM ui it usually works.  for me I thought it's a local issue

**Comment by phillysnow** [comment]
Hey @frankstallone,

Did you have the Slice Simulator set up correctly when seeing this issue?

**Comment by frankstallone** [comment]
@phillysnow honestly it's been so long since I posted this — I do not remember. I am no entirely sure how this feature is supposed to work and having had time to try it. Going to close this. I'll open another ticket when I cross this bridge.
