### ISSUE TITLE
When Creating a new Slice Machine Project with a new Next project, the sm.json configuration is set to previousNext

### ISSUE THREAD

**Issue by Duaner** [prismicio/slice-machine#547]
### Versions

- slice-machine-ui: 0.4.1
- node: 16

### Reproduction

After creating a new next project from scratch with create-next-app and then running slicemachine init. The sm.json default is set to PreviousNext

```
{
  "_latest": "0.3.0",
  "apiEndpoint": "https://.prismic.io/api/v2",
  "libraries": [
    "@/slices"
  ],
  "framework": "previousNext",
   "localSliceSimulatorURL": "http://localhost:3000/slice-simulator"
}
```

### What is expected?

To default to the latest next version

### What is actually happening?
See above

**Comment by lihbr** [comment]
Did some research, it appears this is due to this migration script still being run on new projects: https://github.com/prismicio/slice-machine/blob/HEAD/packages/slice-machine/scripts/migration/versions/0.3.0/index.ts

**Comment by lihbr** [comment]
OK, after further investigation it looks like [`5fd2faa`](https://github.com/prismicio/slice-machine/pull/473/commits/5fd2faa027f1c2f251d1e85ad5114b13330ae0a8#diff-e87eaba9c5d8c8084ef8b2023d1cd2ee4020a2712471c7fcab6c0301d90c6f2b) in [`[Release Branch]: v0.4.0` #473](https://github.com/prismicio/slice-machine/pull/473) moved the install dependencies step of `@slicemachine/init` _**after**_ project configuration.

This prevents the "configure project" step to detect the installed version of Slice Machine (as it's now installed after), making it default to the first one relevant for migrations (0.0.41), see: https://github.com/prismicio/slice-machine/blob/master/packages/init/src/steps/configure-project.ts#L91-L93

**Comment by MarcMcIntosh** [comment]
Did this fix it?
https://github.com/prismicio/slice-machine/pull/546

**Comment by lihbr** [comment]
Looks like it does indeed! Awesome :) (I let you close when relevant)

**Comment by Heyrows** [comment]
The fix has been released, closing this.
