### ISSUE TITLE
Prettier errors in new slice file

### ISSUE THREAD

**Issue by samuelhorn** [prismicio/slice-machine#55]
### Version

- Prismic CLI version (know it by running `prismic --version`): 3.8.3-beta.0

### Reproduction

Create a new nuxt installation with prettier selected, create a slice using slicemachine

### What is expected?

The newly created slice should throw no linting errors

### What is actually happening?

Prettier warns about linting issues in `./slices/SliceName/index.vue` & `./slices/SliceName/index.stories.js`

### Any additionnal information

If someone could point me in the direction of where to change the template I can fix it and create a PR.

**Comment by hypervillain** [comment]
Hey @samuelhorn, the template is well hidden indeed 😊
It's there: https://github.com/prismicio/prismic-cli/tree/mm/meta-2020/lib/commands/slicemachine/templates/nuxt

I noticed it also doesn't set a `name` property. Can you add this too? the component name should be available when the template is used

**Comment by hypervillain** [comment]
It should close #46 too (that I fixed already but it somewhat got lost when merged different branches)

**Comment by samuelhorn** [comment]
Will make a PR when slicecontest is over ;)
Don't have the time right now, lol!

**Comment by samuelhorn** [comment]
Fixed this with #71 

But I don't get what you mean by the name property, its already set on row 27 right?

**Comment by samuelhorn** [comment]
Fixed in [this](https://github.com/prismicio/prismic-cli/pull/71) PR. 

Don't really get the name property, isn't it set already on line 27?

**Comment by lihbr** [comment]
PR merged, thanks again Samuel!

**Comment by samuelhorn** [comment]
My pleasure 👍
