### ISSUE TITLE
If user tracking fails to connect, slicemachine fails and is unusable

### ISSUE THREAD

**Issue by guillermopd** [prismicio/slice-machine#550]
### Versions

- slice-machine-ui: 0.4.2
- node: 16.10.0

### Reproduction

When using DNS ad-blocking, slicemachine dies when invoked in develop mode and the page is loaded

<details open>
<summary>Additional Details</summary>
Console error:

```
[slice-machine] AxiosError: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
...
_currentUrl: 'https://....D6P:@api.segment.io/v1/batch',
```

I've  obscured the API key for segment.io -> Twilio tracking

</details>

### Steps to reproduce

Enable pi-hole, a DNS ad blocker or point api.segment.io to an invalid IP or localhost

### What is expected?

Customer tracking should be optional and not mandatory for the slice machine to work

### What is actually happening?

Slicemachine closes when the local page is loaded

**Comment by lachieh** [comment]
It would be good if this failed silently, but it would be better if tracking was opt-out.

**Comment by ReeceM** [comment]
> It would be good if this failed silently, but it would be better if tracking was opt-out.

I think there is a note on another similar issue on disabling this when running the command as a flag. (Only remember seeing it on an email somewhere 🤷‍♂️)

**Comment by lachieh** [comment]
Can't see any flags that would disable tracking in the code.

Would the @prismicio team be open to PRs? I couldn't see a `CONTRIBUTING.md` guide in any of the packages.

**Comment by ReeceM** [comment]
@lachieh  https://github.com/prismicio/slice-machine/issues/466#issuecomment-1136124618

/cc @comeprismic if this is still correct?

**Comment by lachieh** [comment]
@ReeceM that works! Thanks!

For posterity, the command is: `npx @slicemachine/init script --tracking false`

It would still be good to fix the underlying issue, and I'd be willing to assist with it if PRs are accepted.

**Comment by louisefindlay23** [comment]
I'm still encountering this issue when not using `--tracking false`. Not sure if this is expected?

**Comment by MartijnHols** [comment]
Closing this issue was a bit premature, as it's still an issue that makes adoption of this solution troublesome.

In 1.26 the only workaround I could make work was adding `telemetry=false` to a `.prismicrc` file.
