### ISSUE TITLE
Static Zone Fields Not Appearing In Slice Machine UI

### ISSUE THREAD

**Issue by gracemiller23** [prismicio/slice-machine#554]
### Versions

- slice-machine-ui: 0.4.2
- node: v16.13.0

### Reproduction

https://user-images.githubusercontent.com/35137655/183533527-b05a1dd8-9317-4705-9c91-c6dd1f477964.mov

### Steps to reproduce
- Add a field to the static zone
- Push to Prismic
- Navigate away from Custom Type
- Return to Custom Type pane

### What is expected?
- All fields will be visible in the UI
- All fields will be saved to the filesystem

### What is actually happening?
- The static zone field is not visible, except after refreshing the page
- The fields are saved to the filesystem

**Comment by hypervillain** [comment]
This may be related to the CT state being SYNCED instead of UPDATED

**Comment by hypervillain** [comment]
Same problem with adding slices

**Comment by Heyrows** [comment]
Hi @gracemiller23 thank you for reporting this issue 🙏.
This will be fixed in our next version v0.4.3 so stay tuned 😄.

Cheers.

**Comment by pavery007** [comment]
This bug fix is deployed to Production.
