### ISSUE TITLE
This line causes a null pointer when field type is IntegrationFields

### ISSUE THREAD

**Issue by myatt95** [prismicio/slice-machine#57]
https://github.com/prismicio/slice-machine/blob/b36fa8b30c99f050356befe8671b4b368e6914b1/packages/slice-machine/lib/builder/modules/FieldZone/components/ListItem.js#L30

I wasn't able to push my model to prismic so looked at the code and this line is the culprit.

I changed to `if (!widgets[type]?.Meta) {`

**Comment by lihbr** [comment]
Thank you so much for this new report @myatt95, we'll have a look at that starting next week!

You are transitioning from a "legacy" Slice Machine library to a new one right?

**Comment by hypervillain** [comment]
Hello @myatt95, thanks for reporting this. This should be fixed with v 0.0.39. Can you give it a try?

**Comment by lihbr** [comment]
Has been fixed 🥳
