### ISSUE TITLE
Image mock does not fit given constrainsts, image variant images mock are different

### ISSUE THREAD

**Issue by lihbr** [prismicio/slice-machine#59]
### Version

- Prismic CLI version: v3.8.3-beta.0
- slice-machine-ui: v0.0.39

### Reproduction

- Lauch Slice Machine UI
- Add an image field
- Add a set of width and height constraints
- Add another set of width and height constrainsts
- Check out generated mock

### What is expected?

1. Generated image mock should match width and height constraints like in wroom:
![https://images.prismic.io/prismic-demo-seo/bbada609-00ca-40bb-af83-3e3bf66180a4_meta_5.jpg?auto=compress,format&rect=0,0,800,800&w=200&h=200](https://images.prismic.io/prismic-demo-seo/bbada609-00ca-40bb-af83-3e3bf66180a4_meta_5.jpg?auto=compress,format&rect=0,0,800,800&w=200&h=200)
2. Same field image variants should be made out of the same base image.

### What is actually happening?

1. Generate image mock only match width OR height constraints, no cropping is being made like what the WROOM is doing (missing bounding box):
![https://images.prismic.io/prismic-demo-seo/bbada609-00ca-40bb-af83-3e3bf66180a4_meta_5.jpg?w=200&h=200](https://images.prismic.io/prismic-demo-seo/bbada609-00ca-40bb-af83-3e3bf66180a4_meta_5.jpg?w=200&h=200)
2. Base image is different for each mocked image variant.

### Any additionnal information

/

**Comment by hypervillain** [comment]
👍

**Comment by lihbr** [comment]
Has been fixed 🥳
