### ISSUE TITLE
We can still create a slice that starts with a number but that creates error afterwards

### ISSUE THREAD

**Issue by chamois-d-or** [prismicio/slice-machine#599]
Javascript constant names cannot start with numbers. This creates an issue when slice are created with their name starting with a number.

### Versions

- slice-machine-ui: 0.4.2
- node: 14

### Steps to reproduce

Create a slice starting with a number, e.g. `2Columns`

### What is expected?

UI should not let users create such slices.

### What is actually happening?

UI lets you do so.

**Comment by mdeclercq** [comment]
This issue has been fixed for the Slice creation but a similar issue can happen when renaming a slice. See https://github.com/prismicio/slice-machine/issues/791
