### ISSUE TITLE
When generating mock data for repeatable zone of a slice, it only generates one item

### ISSUE THREAD

**Issue by chamois-d-or** [prismicio/slice-machine#621]
### Versions
 
- slice-machine-ui:  0.5.0
- node: 

### Reproduction

Add fields in a repeatable zone of a slice and save to filesystem

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Add fields in a repeatable zone of a slice and save to filesystem, and preview the slice or take a screenshot
### What is expected?
The mocks should contain more than 1 element (at least this was the case in previous versions of the slicemachine)
### What is actually happening?
Mocks only contain one item which prevents from seeing what the repeatable section will look like when having multiple items

**Comment by mdeclercq** [comment]
Hello,

This is fixed in the latest version of Slice Machine.
One item is added by default, and with the Slice Simulator, you can add as many group items as you want.

Thanks,
