### ISSUE TITLE
Pushing changes overwrites all changes made in different branches in v0.5.0

### ISSUE THREAD

**Issue by ghost** [prismicio/slice-machine#625]
In the latest version of Slice Machine, v0.5.0, we have the nice new feature to push all changes at once.

Unfortunately, we can now _only_ push everything that Slice Machine sees as a change.

This means when two developers are working on different feature branches, any changes to Custom Types or Slices that the first dev makes, will be overwritten when the second pushes their changes.

### Versions

- slice-machine-ui: 0.5.0
- node: 16.13.1

### Steps to reproduce

1. On a branch, make a change to a Custom Type (e.g. Home Page)
2. Go to Changes tab, and push changes using the Push Changes button
3. On a separate branch, make a change to a different Custom Type (e.g. About Page)
4. Go to Changes tab

### What is expected?

Only changes that the developer has made to About Page are displayed.
Developer can push their changes to About Page, without altering Custom Types that others may have altered independently (in this case Home Page).

### What is actually happening?

Two changes are displayed:
- one for About Page because that has been edited
- one for Home Page, even though that has not been edited locally
Note that there is no way to push only changes to About Page.

**Comment by comeprismic** [comment]
Hey @jarod-treble 

Thanks for submitting an issue about this topic. We are currently working on the "Changes" page to solve the problem you are describing. We have already a few ideas and concepts ;) 

Would you like to jump in a quick call with us next week to discuss it and tell us what you think? 

You (and anyone interested in the topic) can [pick-up a slot](https://calendly.com/come-sabran/concept-testing-with-slice-machine-product-manager?month=2022-11&date=2022-11-02)  in my calendar. 

All the best, 

Côme, PM of the Slice Machine

cc @alexhillel @reachalan @connor406 you're more than welcome too!

**Comment by ghost** [comment]
Hi Côme, any update on this one? We've upgraded to 0.7.1 hoping this wouldn't be an issue still, but it is!

Cheers
Jarod

**Comment by luialpi** [comment]
Hi @comeprismic, do you have any updates on this?

**Comment by asotog** [comment]
we are having same issue when multiple teams working on different slices/types

**Comment by comeprismic** [comment]
Hi! Good news here, since the begining of the quarter, we are working on a solution to this problem. More updates to come soon ;)

**Comment by timvandenhof** [comment]
Is there any update about this? It would be great if we could just select which items to push. It will remain an issue if both team members change the same custom type/page type/slice though.

**Comment by comeprismic** [comment]
Hi @timvandenhof,

Thanks for the follow-up message. We don't have any update yet in production. The team is now working on modelling improvements but on the product side we have laid down our vision for the developer collaboration workflows. Plan is to start delivering on this vision in 2025. I can't say a release date unfortunately, I hope you understand. 

Best, 

Côme
