### ISSUE TITLE
Screenshots from storybuilder rely on "name" value matching component naming convention

### ISSUE THREAD

**Issue by project707** [prismicio/slice-machine#64]
### Version

- Prismic CLI version (know it by running `prismic --version`): 3.8.3-beta.0

### Reproduction

Create a new slice MySlice.
Change the "name" value in the model to what you'd want your editors to see, e.g. "My Slice"
Try taking a screenshot.

### What is expected?

The screenshot is taken because a common machine-readable id is used as the reference instead of the key defining display text that is shown in Prismic.

### What is actually happening?

This is sent: http://localhost:9999/api/screenshot?sliceName=MySlice&from=slices
Storybook doesn't find this and returns a 400

**Comment by lihbr** [comment]
Hey @project707, I'm really sorry for the lack of support back then, we'll have a look into it~

*Update `02/17/2021`:*
1. Needs investigation @hypervillain

**Comment by hypervillain** [comment]
Thanks for reporting this @project707, from what I understand, renaming the slice and taking a screenshot should work fine if you reload the builder page before taking the screenshot. I'll try to reproduce on my side today
