### ISSUE TITLE
Missing storynames in index.stories.svelte files

### ISSUE THREAD

**Issue by kueckelheim** [prismicio/slice-machine#641]
### Versions

- slice-machine-ui: v0.5.0
- node: v16.15.0

### Reproduction

When installing slicemachine on a svelte project in combination with storybook, slicemachine does not include the name of the Slice/Slice-Version in the name property of the storybook-story.

<img width="1728" alt="Screenshot 2022-10-14 at 09 20 43" src="https://user-images.githubusercontent.com/46760457/195787893-675ae23f-1712-4273-ae01-b6f6ff0789a1.png">

Therefore, storybook can not render those stories and you would have to manually enter the name each time you update a slice with the slicemachine.

<img width="1728" alt="Screenshot 2022-10-14 at 09 20 15" src="https://user-images.githubusercontent.com/46760457/195787860-320cf12d-6eae-437a-8521-acfc71e35b31.png">

When the name is manually added, storybook successfully detects and renders the story. For a smooth and efficients work-flow, it would be awesome if those names could be added automatically.

### What is expected?

slicemachine should generate stories with the name attribute filled in.

**Comment by mdeclercq** [comment]
Hi,

Thanks for reporting the issue.
In the latest Slice Machine version, we removed Storybook support in favour of Slice Simulator.
At the same time, we don't officially support the Svelte framework yet.

I'm closing the issue until we have new updates on that front.
