### ISSUE TITLE
Slice description is not updated when Slice is renamed

### ISSUE THREAD

**Issue by mdeclercq** [prismicio/slice-machine#649]
### Versions

- slice-machine-ui: `0.5.1`
- node: `v16.17.1`

### Steps to reproduce

- Launch Slicemachine
- Create a new Slice named `Hero`
- Open the `slices/Hero/model.json` file, it contains `"description": "Hero"`
- Rename the slice to something else like `HeroRenamed`
- Open the `slices/HeroRenamed/model.json` file

### What is expected?
- The previous Slice name isn't used in the model file. It should contain `"description": "HeroRenamed"`
```json
  "name": "HeroRenamed",
  "description": "HeroRenamed",
```

### What is actually happening?
- it still contains `"description": "Hero"`
```json
  "name": "HeroRenamed",
  "description": "Hero",
```

**Comment by Ali-Parandeh** [comment]
Related to the bug I reported
https://github.com/prismicio/slice-machine/issues/1037

**Comment by mdeclercq** [comment]
Hi,
We're closing this issue as the description field will be deprecated in the new page builder.
