### ISSUE TITLE
Cannot reset Slice image field dimensions to "auto“

### ISSUE THREAD

**Issue by mdeclercq** [prismicio/slice-machine#672]
### Versions
- slice-machine-ui: `0.5.2`
- node: `v16.17.1`

### Steps to reproduce
- Launch Slicemachine
- Create a new Slice named Hero
- Add a new Image field named Image in the Non-Repeatable Zone
- Open the Image settings and set the `height` and `width` to `500`
- Save the image settings. Save the slice. 
- Open the Image settings and erase the height and width input values. The dimensions switches to `auto`
- Save the image settings
- Open the Image settings again

### What is expected?
- The image dimensions is still set to `auto`
- After saving the slice, the `slices/Hero/model.json` file contains empty dimension settings: `”constraint":{}`

### What is actually happening?
- The image dimension fields are still set to 500
- The slice cannot be saved since no changes are detected
- The only way to set the image dimension to `auto` in the UI is to set the width and height to `0`. But this translates to `”constraint":{"width": 0, "height": 0}` in the model file. There should be another way.

https://user-images.githubusercontent.com/6433957/199792836-0c31cb63-4b28-4cd4-8594-cc2700b5b8b9.mov

**Comment by hypervillain** [comment]
Any reason you're still on 0.5.2? Can you try to upgrade to see if the problem is fixed?

**Comment by xrutayisire** [comment]
@mdeclercq tested it in November, so I guess that's why it was the 0.5.2. On my side, I was able to reproduce with latest 1.0.0. My PR was based on the 1.0.0 so.

**Comment by hypervillain** [comment]
Thanks @xrutayisire
