### ISSUE TITLE
RFC: Port SliceZone to Next.js

### ISSUE THREAD

**Issue by hypervillain** [prismicio/slice-machine#7]
Part of the port of SliceMachine to Next consists in porting the SliceZone.

### What's a SliceZone

A component that matches front-end components with Prismic data components (that we call slices). You can see it as an hybrid between a "components registry" and a router:

- at build time, it scans and lists available components to create a custom resolver function
- when a page hits, it fetches the corresponding content on Prismic
- it then matches Prismic slices with components, and renders them accordingly

### Features

- Auto-fetch Prismic data
- Auto-match components
- Theme (via context or props)
- Vue slots-like pattern

### Static export and differences with Nuxt

Next 9.3 introduced `getStaticProps` to pre-render pages at build time. Instead of relying on a `PageFetch` wrapper component, the `next-slicezone` exports a `useGetStaticProps` function that formats arguments and returns a Next `getStaticProps` function.

The Nuxt module makes use of Nuxt templating to create the resolver function. A more idiomatic way to handle such cases in Next would be to create the registry (an object with components ids and paths) at `getStaticPaths` call and pass it down. The SliceZone would then pick up the registry and make calls to `loadableComponents`.

### On slots

The Nuxt SliceZone makes use of Vue named-slots. When working with external libraries like [essential slices](https://github.com/prismicio/essential-slices), 
a common pattern is to defer part of the renderers to the user. Different solutions exist in React (notably render props pattern), and we might offer several.

### Example page

This is subject to change, especially regarding how/where Prismic client is instantiated.

```javascript
import { Client } from '../prismic'
import SliceZone, { useGetStaticProps, useGetStaticPaths } from 'next-slicezone'


const Page = ({ uid, registry, slices }) => (
  <div>
    <h1 className="title">
      Welcome to page "{uid}"!
    </h1>
	<SliceZone registry={registry} slices={slices} />
  </div>
)

export const getStaticProps = useGetStaticProps({
  client: Client(),
  uid: ({ params }) => params.uid
})

export const getStaticPaths = useGetStaticPaths({
  client: Client(),
  type: 'page',
  fallback: true,
  formatPaths: ({ uid }) => `/${uid}`
})

export default Page
````

**Comment by sadache** [comment]
@hypervillain which paths you will be scanning in the folders of a Next.js project for components? What is the priority hierarchy (local then dependencies?) ?

What is the folder structure of a given component? (the model, the component file, etc)

**Comment by sadache** [comment]
@hypervillain also can you please add (for context) an example of the syntax for declaring a SliceZone in a Next page? 🙏

**Comment by hypervillain** [comment]
I'll add a section regarding scan & match. I've described how the filesystem is scanned here in the meantime: https://github.com/prismicio/slice-machine/tree/master/packages/vue-slicezone#auto-match-components

**Comment by sadache** [comment]
React and Next ignorant here, but can't we do something as simple as we have in Nuxt? something like:
`<SliceZone type={type} uid={uid} />`
And the component auto fetches the content from Prismic?

**Comment by sadache** [comment]
> React and Next ignorant here, but can't we do something as simple as we have in Nuxt? something like:
> `<SliceZone type={type} uid={uid} />`
> And the component auto fetches the content from Prismic?

It seems we can't for now, until suspense for pre-rendering is available in React

<img width="435" alt="Screen Shot 2020-06-10 at 14 51 30" src="https://user-images.githubusercontent.com/60507/84269809-0808ec00-ab2a-11ea-8509-2b26c4e0920d.png">

**Comment by wasinsandiego** [comment]
It's still unclear if React on Next.js is supported yet. Is your support for Next.js the same as support for React concerning the slice machine?
