### ISSUE TITLE
Não consigo instalar o seguinte comando @slicemachine/init

### ISSUE THREAD

**Issue by mauricio-br182** [prismicio/slice-machine#709]
Process on port 127.0.0.1:5555 killed
You're about to configure Slicemachine... Press ctrl + C to cancel
>> Press any key to open the browser to login or q to exit:

Error! listen EADDRINUSE: address already in use 127.0.0.1:5555

**Comment by mdeclercq** [comment]
Hi @mauricio-br182,

Could you please update the issue description following the [bug template](https://github.com/prismicio/slice-machine/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) ? 
We need to know more about your environment and a scenario including the commands that you have executed.

Thanks,

**Comment by pedrodahmer** [comment]
Fala @mauricio-br182 !! Eu estava com o mesmo problema! Entrando no endereço que o erro especifica (127.0.0.1:5555) descobri que era o Tabnine (extensão de auto-complete do VSCode) que estava ocupando essa porta do meu sistema. Acho que o melhor jeito de resolver o problema é nessa linha: 1 - Entrar no endereço especificado no erro; 2 - Descobrir o que está ocupando essa porta; 3 - Desligar momentaneamente para poder fazer o setup do slicemachine.

Espero que funcione!!

**Comment by mdeclercq** [comment]
Thanks @pedrodahmer for the additional details. It could help others.

Indeed, SliceMachine uses the port 5555 to login.
In case Tabnine was the issue, the default port can be changed in the [config file](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location). See https://github.com/codota/TabNine/issues/422 

I'm closing this issue, let us know if you feel it should be reopened.
