### ISSUE TITLE
Discussion: custom widgets in `slice-machine-ui`

### ISSUE THREAD

**Issue by maurocolella** [prismicio/slice-machine#71]
Hi Prismic.

I apologize for working outside of the default issue template. I am taking the initiative because I want to make the most of Prismic. My team and me want to make the most of Prismic.

We have a use case where some of the data in our slices represents bezier curves. Nothing fancy, just quadratic bezier curves represented in svg (one endpoint, and one control point, **X1-Y1 - X2-Y2**).

I want our users to have a widget they can use to nicely control the bezier. 

I could possibly fork `slice-machine-ui` locally, and work a component there, but designers on our team will have to use the feature when working with content.

Is there any way to create and publish custom field types/custom field widgets through Prismic?

**Comment by lihbr** [comment]
Hey Mauro, have no worries~! Really happy to hear that you're looking to make the most out of Prismic ☺️

That's an interesting use case you have here and it would make perfect sense to have custom widgets here indeed. I'm afraid although that this is not something possible with Prismic *yet*.

You could, theoretically, fork `slice-machine-ui` and from there work your way toward adding another widget to it, but it will remain inside the Slice Machine UI and will not reflect inside your Prismic writing room ([https://<your-repo-name>.prismic.io](https://prismic.io/dashboard)).
> Just to clarify (in case that wasn't clear) Slice Machine UI works only as a custom type builder for slices, only (as of right now). It has no impact on the content writers' experience. Basically, it's an improvement to the developer experience and doesn't impact the product usage itself (directly at least). So, yeah, you cannot add another widget to the product too through it.

Not sure is all of that make sense, please let me know ^^'

Custom widgets are something we might consider adding in the future. I know that so far we've been quite reluctant at these for user experience reasons (as they can easily impact badly performances or UI accessibility and such) but we'll consider more feedback about those. As we're not set on anything yet I wouldn't expect this feature to become available soon.

In the meantime here are two, I agree quite poor, workarounds:

- You could use 4 number fields, one for X1, Y1, X2, Y2, it would provide no UI to visualize the curve be would be quite bulletproof.
- Alternatively, you could use a Key Text field, or a Rich Text field allowing only one paragraph of preformatted text, where your content writers will be able to input their cubic-bezier expression. While more convenient it's also more error prone.

Let me know if anything 🙂

**Comment by maurocolella** [comment]
Thanks Lucie. I thought about that: thanks a lot for your help and your
thoughtful feedback.

I think that well-isolated input widgets, for example
widgets-as-render-props, or widgets that must strictly implement a certain
interface or extend a minimal parent class could work.

For my team, as I said, Prismic seems like the kind of lean starting point
we want, but we want it lean because we want to grow out of it.

I see a number of use cases where custom input makes sense. Notably, when
it comes to custom data visualization.

Anyway. Sincerely hope you will consider it, and please do keep me posted!

Cheers.

**Comment by lihbr** [comment]
*Update `02/17/2021`:*
1. @Duaner if you can have a quick look at this thread, I'm thinking it's out of scope so maybe closing it?

**Comment by hypervillain** [comment]
Closing for the moment as we're not planning to handle custom widgets ATM
