### ISSUE TITLE
error on Enter when rich text is not allowing multi paragraph

### ISSUE THREAD

**Issue by techmind-git** [prismicio/slice-machine#73]
### Version
3.8.5

### Reproduction
I define a field in my slice of type rich text without the "multiple paragraph" checked. After pushed to Prismic I try to add content to the field. When clicking ENTER I get a console error. After running into this issue with a slice I tried the same with a static field and it has the same error on ENTER. With multiple paragraph option selected no errors are present

### What is expected?
At a minimum no error in the console :-), but some notification stating why I can't ENTER would be nice as well for content editors to know why they cannot add more lines (that it is not multi paragraph is not clear for an editor so they might not know what the issue is)

### What is actually happening?
Console error:
```
main.js:formatted:74983 Uncaught TypeError: Cannot read property 'validContent' of undefined
    at t.canSplit (main.js:formatted:74983)
    at Array.R (main.js:formatted:43401)
    at main.js:formatted:43464
    at n.<anonymous> (main.js:formatted:145258)
    at main.js:formatted:144190
    at x.someProp (main.js:formatted:142819)
    at g.keydown (main.js:formatted:144189)
    at HTMLDivElement.e.dom.addEventListener.e.eventHandlers.<computed> (main.js:formatted:144166)
    at HTMLDivElement.i (main.js:formatted:41560)
```

**Comment by lihbr** [comment]
Hey, thanks for the report @techmind-git, we'll have a look into it!

Tagging @Duaner here and forwarding your request to our productboard ☺️

**Comment by hypervillain** [comment]
Closing as this is not directly related to the local builder
