### ISSUE TITLE
Error when starting slice builder

### ISSUE THREAD

**Issue by techmind-git** [prismicio/slice-machine#74]
### Version
v3.8.5

### Reproduction
starting slice builder locally with "prismic sm --develop"

### What is expected?
No errors

### What is actually happening?
```
> start-slicemachine --port 9999

An error occured while migrating file system. Continuing...
Full error: SyntaxError: Unexpected token 'export'
[slice-machine] Launching server

[slice-machine] Now running on http://localhost:9999 !
```

### Any additional information
I'm running on Windows machine and using npm. I didn't get the error when downgrading slice-machine-ui to 0.0.42, but I do when using 0.0.43. Although I get the error I don't see any issues using slicemachine so far so it doesn't seem to be blocking anything.

**Comment by hypervillain** [comment]
Hey @techmind-git, thanks for reporting this. The error should be fixed in upcoming version. As you mentioned, it's self-contained and shouldn't have any incidence on your project.
