### ISSUE TITLE
'Define first value as default' checkbox doesn't retain value in mask on save

### ISSUE THREAD

**Issue by priyaprafful** [prismicio/slice-machine#76]
### Version

- Prismic CLI version (know it by running `prismic --version`): 
prismic --version; 3.8.5

### Reproduction

Created Slice-machine cluster repository and add a select field and set the default value.

### What is expected?

Default value in a select field should remain saved after being saved custom-type.

### What is actually happening?

The client has created his project with the Slice-Machine. When he tried to set the default first value on a select field in the repository, It gets set, but when he save custom-type or mask, the default value is being removed. This issue occurs only with the Slice-Machine created repo, not with the other repo.

### Any additional information

Community forum thread: https://community.prismic.io/t/define-first-value-as-default-checkbox-doesnt-retain-value-in-mask-on-save/3637

**Comment by lihbr** [comment]
*Update `02/17/2021`:*
1. Managed to reproduce, still an issue @hypervillain @Duaner

**Comment by hypervillain** [comment]
fixed
