### ISSUE TITLE
Renaming a Slice accepts strings starting with number

### ISSUE THREAD

**Issue by mdeclercq** [prismicio/slice-machine#791]
### Versions

- slice-machine-ui: `0.6.0`
- node: `v18.12.1`

### Steps to reproduce

- Run SliceMachine
- Create a Slice 
- Open the "rename slice" modal 
- Type a name starting with a number, for example `3Columns`

### What is expected?
- The submit button is disabled, just like in the Create slice modal

### What is actually happening?
- The submit button is enabled, we can rename the slice with an invalid name
- The breaks the Slice simulator since the slice cannot be imported

<img width="513" alt="image" src="https://user-images.githubusercontent.com/6433957/210256515-4f0ad77a-c2a3-43b6-a32a-4288e89d08e1.png">

<img width="539" alt="image" src="https://user-images.githubusercontent.com/6433957/210256561-99169a06-b942-4626-9792-4c0420be9d6c.png">

**Comment by danielphilipjohnson** [comment]
In the [create a slice modal ](https://github.com/prismicio/slice-machine/blob/297200c935404eba8215164e49da677a1075e0e9/packages/slice-machine/components/Forms/RenameSliceModal/RenameSliceModal.tsx#L55)

It has the following logic

```te
if (sliceName.match(/^\d/)) {
      return { sliceName: "Value cannot start with a number" };
}

```

Rename a slice is modal validation is missing the following logic

PR that fixed it for Create a slice #600 might need to be replicate for rename slice. I can replicate the PR if needed. :)
