### ISSUE TITLE
Publish the changelog

### ISSUE THREAD

**Issue by loick** [prismicio/slice-machine#815]
Hi, 

First of all, thanks for the great work 🙏

I'm posting this issue to highlight the fact that the changelog of the releases on the package `slice-machine-ui` does not seem to exist. 

As you can see on the screenshot below (PR generated by Renovate):

![CleanShot 2023-01-20 at 10 12 59@2x](https://user-images.githubusercontent.com/4931832/213658543-7d30a3b3-1e6f-41cb-bf9a-75356bc08bd8.png)

In comparison, here is the PR made by NextJS, as you can see Renovate is able to display the changelog, handy to bump the package version: 

![CleanShot 2023-01-20 at 10 14 56@2x](https://user-images.githubusercontent.com/4931832/213659060-ffafb945-a10c-416f-bdc8-6a55e149bad4.png)

Is it possible to publish the changelogs? Thanks 🙏

**Comment by mdeclercq** [comment]
Hi @loick,

Thanks for the detailed reporting of the issue. 
This should be fixed in the next release, I'll close the issue once it is tested.

**Comment by mdeclercq** [comment]
Hi,
This has been fixed for the package `slice-machine-ui`, starting from the version `1.1.0`.
<img width="1118" alt="Screenshot 2023-05-29 at 18 09 24" src="https://github.com/prismicio/slice-machine/assets/6433957/6197f6ea-0c7a-4348-94a3-dbd89d14c11e">

Feel free to comment/re-open the issue in case something is missing.
Thanks again,
