### ISSUE TITLE
Page / Slice Rename does not change UIDs

### ISSUE THREAD

**Issue by riuci-admin** [prismicio/slice-machine#867]
When I rename a Slice or Page, the ids or uids are not being updated, and even after manually updating references of old ids in the source code, I get errors telling me that the id is already being used

<img width="413" alt="image" src="https://user-images.githubusercontent.com/125395339/225918932-34ad0375-b206-4fed-9b32-3dabbce9632b.png">

This happens when I want to reuse an id that was used before, even after updating all references from slicemachine and the sourcecode (which shouldn't be done by hand). 

This is very annoying and I've had to recreate slices and pages and then add again the contents, which is very time consuming. And even then the problem persists, and the main issue is that I cannot assign the right slot to a page so this is blocking my client to go live

### Versions

- slice-machine-ui: v0.7.1
- node: v18.14.0

**Comment by hypervillain** [comment]
Thanks for your report. Can you update to 1.0?

**Comment by hypervillain** [comment]
You can find more information here:
https://community.prismic.io/t/error-this-value-is-already-used-by-another-document/5465
