### ISSUE TITLE
RFC: Name component functions with the Slice Name

### ISSUE THREAD

**Issue by a-trost** [prismicio/slice-machine#89]
## Current state
Right now when you create a slice with `prismic sm --create-slice` you are asked to give a location to build the slice, as well as a PascalCase name for that slice. The CLI then creates a folder with that name, and uses it in a few other places like the Storybook story file.

It does not use it to name the React functional component that it creates, so you get essentially this:
```
const MySlice = ({ slice }) => (
<div>
...
</div>
)

export default MySlice;
```

This means that all of your Slices have functions with the same name. This makes it less intuitive to debug errors like these:
```
Warning: Failed prop type: The prop `slice.primary.title` is marked as required in `MySlice`, but its value is `undefined`.
```

## Proposed solution
We can apply the same Slice name to the function so that if I give a name of `HeroSection` I'll get a component like this:
```
const HeroSection= ({ slice }) => (
<div>
...
</div>
)

export default HeroSection;
```

This will make debugging easier and also give a bit more context within the file. We are already asking for a PascalCase name, so this matches the React standard for components already.

Thoughts on this? Any potential pitfalls I'm missing with this approach?

**Comment by davidparys** [comment]
Yes ! After one project with 20 or so slices this saves a solid 1-2 min per slice

**Comment by ReeceM** [comment]
Hey Alex, think maybe this might be the same thing here https://community.prismic.io/t/slicename-in-in-index-js-is-not-the-same-as-name-given-in-cli/3790/6

And here: https://github.com/prismicio/prismic-cli/issues/78

I am not sure where in the upstream stream of time it is \:) or if it is related to this.

Pity GitHub pulled the issue looks like this search thing... 🤷‍♂️

**Comment by ReeceM** [comment]
Went and found it again, I looked at it when the changes were made, unless these are going to be integrated into this monorepo?

https://github.com/prismicio/prismic-cli/blob/9baad5e01fff33a620d08e0e1fc423159fa54d26/src/generators/slicemachine/create-slice/templates/next/index.js#L3-L5

Personally I can see only benefit from this as it will help too when using debug tools and seeing the name. As well as many other things that would be useful.

---

I think this might be the actual bit that's doing the actual work though \:)

https://github.com/prismicio/prismic-cli/blob/9baad5e01fff33a620d08e0e1fc423159fa54d26/src/generators/slicemachine/create-slice/index.ts#L116-L128

**Comment by a-trost** [comment]
Great call, @ReeceM! That's exactly what I was talking about. Seems like it's on its way. I appreciate you surfacing that!

**Comment by hypervillain** [comment]
The create-slice command is now part of the local builder and it does handle naming components:
https://github.com/prismicio/slice-machine/blob/with-custom-types/packages/slice-machine/templates/slice/next/index.js#L4

As Alex said, thanks a lot for taking the time to read the project @ReeceM, it's much appreciated
