### ISSUE TITLE
Checking use first value as default in SELECT field has no effect on model.json

### ISSUE THREAD

**Issue by chamois-d-or** [prismicio/slice-machine#900]
### Versions

- slice-machine-ui: 0.7.1
- node: 18.15.0

### Reproduction

![image](https://user-images.githubusercontent.com/89452979/229733417-0e0a9c05-5d70-461e-bfb3-ce4804b0029c.png)

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
1. create a select field and save it
2. check the "use first value as default" checkbox and save

### What is expected?

model.json shouyld show a change showing the the checkbox is taken into account

### What is actually happening?
nothing changes, which means that in the editor the default value will not be set...

**Comment by hypervillain** [comment]
Hey @chamois-d-or thanks for your report, we have someone working on it at the moment!

**Comment by xrutayisire** [comment]
Fixed in https://github.com/prismicio/slice-machine/pull/944
