### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [prismicio/slice-machine#915]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by mdeclercq** [comment]
Hi @igibek,

Thanks for reaching out. The **Private vulnerability** reporting feature is enabled for the repository so I will be closing this issue.
Let us know if anything is missing.

Thanks!

**Comment by barrymichaeldoyle** [comment]
There are currently moderate vulnerabilities in the latest version :/

**Comment by xrutayisire** [comment]
Hi, thanks for your message.

The last Slice Machine version 1.21.1 fix the vulnerability: https://github.com/prismicio/slice-machine/releases/tag/slice-machine-ui%401.21.1
