### ISSUE TITLE
Disable tracking after init

### ISSUE THREAD

**Issue by ruckc** [prismicio/slice-machine#918]
How do you disable tracking an already init'd project.

You only disclose tracking in the console during the `init` of a new project with this message `ℹ We use tracking tools to improve user experience. Learn more: https://prismic.io/docs/slice-machine#tracking`.  The prismic website doesn't disclose tracking when creating a new project and giving you the command to use to `init`.

**Comment by hypervillain** [comment]
Hi, thanks for the report! We're still working on standardising our tracking opt-out feature. It has been implemented for our next release and you'll be able to completely opt-out of tracking by adding a .prismicrc file in your home or project folder with `telemetry=false`. At the minute, you can add `"tracking": false` to your `sm.json` file, which is what the init command does if you pass the argument. Hope it helps!
