### ISSUE TITLE
Issue with Priscmic.Date or code snippet.

### ISSUE THREAD

**Issue by MarcMcIntosh** [prismicio/slice-machine#93]
### Version

- Prismic CLI version (know it by running `prismic --version`): 
"slice-machine-ui": "^0.0.45"

"prismic-reactjs": "^1.3.3",

### Reproduction
The snippet says to add this to a slice.
`<span >{ ParseDate(slice.primary.myDate) }</span>`
But it breaks the page with this error warning.
`Objects are not valid as a React child (found: Fri Jul 13 2018 02:00:00 GMT+0200 (Central European Summer Time)). If you meant to render a collection of children, use an array instead.`

Add a date and pace the snippet in to the slice.

### What is expected?
A date should be shown

### What is actually happening?
Looks like the Date isn't being stringified.

**Comment by lihbr** [comment]
cc @hypervillain maybe?

**Comment by chamois-d-or** [comment]
This has been fixed
