### ISSUE TITLE
Update storybook's slice story after saving mock content on simulator

### ISSUE THREAD

**Issue by rafaelgiro** [prismicio/slice-machine#932]
### Is your feature request related to a problem? Please describe.
Hi! I'm working on a Primisc website where our slices have a lot of scroll triggers and animations with libraries like GSAP. The thing is that I can't trigger the animations on the Slice Machine's simulator, so I'm using Storybook to develop my slices.
The simulator is awesome, especially in how easily it generates mock data so I can use it on Storybook, but my problem is that after I save my new mock content, the Storybook doesn't update. For my stories to update, I have to make some changes to my slice on the Slice Machine and then click "Save to File System" since the button is disabled by default.

### Describe the solution you'd like
It would be a good Developer Experience if, after I save my new mock content, my story is updated right away with the new data.

### Describe alternatives you've considered
I've considered enabling the button "Save to File System" on the Slice Machine after updating new mock content on the simulator. I've also found some code comparing a `mockConfig` object to enable this button, but it seems that this object was only used before the Slice SImulator.

### Additional context
I've tried an implementation by also calling `Storybook.generateStories` on `/slices/mock` endpoint using some existing functions: https://github.com/rafaelgiro/slice-machine/pull/1/files

**Comment by lihbr** [comment]
Hi!

Thanks for sharing this request. We are not planning on adding any more features related to StoryBook as we focus and invest on our Slice Simulator, but if you want to contribute and make a PR we will gladly consider and review it.
