### ISSUE TITLE
Having `prismicio.ts` and `prismicio.d.ts` doesn't work

### ISSUE THREAD

**Issue by icopp** [prismicio/slice-machine#934]
### Versions

- slice-machine-ui: 1.0.0
- node: 16.17.1

### Steps to reproduce

- Use the template project, but update `prismicio.js` to be `prismicio.ts` at the root level

### What is expected?

- Importing `Content` from `@prismicio/client` uses appropriate types

### What is actually happening?

- It doesn't work, because the generated `prismicio.d.ts` is ignored in favor of `prismicio.ts`
- This is **intended behavior** on the part of Typescript (see, for example, [this issue](https://github.com/microsoft/TypeScript/issues/42329)) and can't easily be turned off
- This **will break** every project using the example file structure and Typescript upon upgrading to slice-machine-ui 1.0.0

### What is the fix?

Change the generated `d.ts` file to a different name or path, or change the name of the `prismicio.js` file in the template project. Either way, they can't have the same name and be in the same folder

**Comment by hypervillain** [comment]
Thanks a lot Ian, we're releasing a fix just now. Types definitions will now live in `prismicio-types.d.ts`. You can rename the file, it will also be recreated next time you make a change in Slicemachine
