### ISSUE TITLE
Dynamic Internationalized Values not available in Lifecycle Hooks

### ISSUE THREAD

**Issue by pvpg** [prismicio/slice-machine#94]
### Version
3.8.10

### Reproduction
We want to be able to get the dynamic language values in `useGetStaticProps` and `useGetStaticPaths` that are set up in the next.config.js to use them as you would in `getStaticProps` and `getStaticPaths`.

**Comment by hypervillain** [comment]
Done in `0.0.15`, use `lang` like you use `uid`
