### ISSUE TITLE
[adapter-next] Generate `prismicio.js` in `src` directory if the project uses `src`

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/slice-machine#947]
### Is your feature request related to a problem? Please describe.

Currently, `@slicemachine/adapter-next` generates a `prismicio.js` file at the root of the project. If a project is set up with Next.js' recommended `@/*` alias ([see the `--import-alias` option in `create-next-app`](https://nextjs.org/docs/api-reference/create-next-app#non-interactive)), the file can be imported anywhere in the project using `@/prismicio`.

However, if a project **also** uses the recommended `src` directory, the `@/prismicio` import no longer works. The alias is mapped to `./src`, which does not contain the generated `prismicio.js` file.

### Describe the solution you'd like

Generate the `prismicio.js` file at `src/prismicio.js` if the project contains a `src` directory.

`@slicemachine/adapter-next` already does something similar when generating the `slice-simulator.js` file. [See this excerpt](https://github.com/prismicio/slice-machine/blob/8c5f46b1ad840f0b1555527645f5bfd1e0ad1c1b/packages/adapter-next/src/hooks/project-init.ts#L179C1-L184).

### Describe alternatives you've considered

- Import `prismicio.js` using relative paths, which is more mental effort than `@/prismicio`.
- Recommend users move it manually, which is messy.

### Additional context

None

**Comment by Ali-Parandeh** [comment]
+1

**Comment by ugistelmokaitis** [comment]
@Ali-Parandeh - Depends on which next version you are using. But probably its related to your tsconfig.json.

Here is mine:
    ```
"compilerOptions": {
        "target": "es5",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "jsx": "preserve",
        "incremental": true,
        "baseUrl": ".",
        "paths": {
            "@/*": ["./src/*"] - potentially this  the answer why it is not working in your case
        },
        "plugins": [
            {
                "name": "next"
            }
```
feel free to share your code happy to look into it :)

**Comment by angeloashmore** [comment]
This was completed in https://github.com/prismicio/slice-machine/pull/1017
