### ISSUE TITLE
[adapter-next] Generate `prismicio-types.d.ts` in `src` directory if the project uses `src`

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/slice-machine#962]
### Is your feature request related to a problem? Please describe.

`create-next-app` now defaults to creating a root `src` directory that holds `app`, `pages`, `components`, etc.

`prismicio-types.d.ts` feels out of place when generated in the root directory if the `src` directory exists.

### Describe the solution you'd like

Generate `prismicio-types.d.ts` in the `src` directory if the project has a `src` directory.

### Describe alternatives you've considered

The file can be manually moved, but it will continue to be generated in the nonoptimal location.

### Additional context

This feature request is similar to https://github.com/prismicio/slice-machine/issues/947

**Comment by Ali-Parandeh** [comment]
+1

**Comment by angeloashmore** [comment]
This was completed in https://github.com/prismicio/slice-machine/pull/1017
