### ISSUE TITLE
Version info fetches are failing with 500 error.

### ISSUE THREAD

**Issue by madiyetov** [prismicio/slice-machine#966]
### Versions

- slice-machine-ui: v1.0.3
- node: v18.12.1
- nuxt: v2.16.3

### Reproduction

Versions fetches are failing with 500 error: `��error��name�Error�message� Invalid GitHub Release response.`

![image](https://user-images.githubusercontent.com/17025375/236845520-461ec079-753a-46d0-bd28-4f23dd2c14db.png)

### Steps to reproduce

I've just migrated from the old slice-machine and started it with `pnpm slicemachine`

### What is expected?

An information about the Slice machine versions.

### What is actually happening?

500 error

**Comment by mdeclercq** [comment]
Hi @madiyetov,

Thanks for reporting this issue.
Can you confirm if this error is persistent or if it goes away after some time?

We observed that this can happen when SM makes too many calls to the github api and exceeds the [rate limits](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-personal-accounts). If this happens, it should resolve itself after an hour. For info, a cache was introduced in `1.0.0` to reduce the number of calls to the api.
This can also happen when the Github api is not responding.

For example, one url SM relies on is https://api.github.com/repos/prismicio/slice-machine/releases.

**Comment by madiyetov** [comment]
I've checked, right now I can't see these error
