### ISSUE TITLE
jpeg screenshots does not seem to be moved with migration

### ISSUE THREAD

**Issue by chamois-d-or** [prismicio/slice-machine#969]
I could not understand why only some of my screenshots were moved with the update from 0.7.0 and not the others, I'm under the impression that png are moved but not jpeg files.
I then see the screenshots as missing.

<img width="565" alt="image" src="https://github.com/prismicio/slice-machine/assets/89452979/d651b534-0454-445d-8782-4655b43dda91">

### Versions

- slice-machine-ui:  v1.0.3
- node: v16.20.0

### Reproduction

migrate to 1.0.3 from 0.7.0 with png and jpeg screenshots

### What is expected?
all screenshots are moved 

### What is actually happening?
only png will be moved.

**Comment by mdeclercq** [comment]
Hi @chamois-d-or,
Thanks for reporting. Indeed jpegs were missed in the migration.
We created a ticket internally to handle this use case - DT-1304.

**Comment by hypervillain** [comment]
Non png extensions are not supported anymore by the new plugins architecture, these files are not considered valid (and therefore not moved). Would you consider it ok to update these files to png format and move them manually?

**Comment by chamois-d-or** [comment]
@hypervillain, yes that's exactly what I did, I renamed the files to .png and moved them manually.

**Comment by hypervillain** [comment]
Awesome. Feel free to reopen if needed
