### ISSUE TITLE
Automatically add Slice Simulator URL to slicemachine.config.json file on slicemachine init

### ISSUE THREAD

**Issue by a-trost** [prismicio/slice-machine#980]
### Is your feature request related to a problem? Please describe.

After going through the flow of `npx create-next-app@latest` and then `npx @slicemachine/init@latest`, a Slice Simulator file is automatically created for me, but the URL isn't added automatically to my `slicemachine.config.json` file. 
Can we make that happen automatically?

### Describe the solution you'd like

1. I create a new Next.js app with `npx create-next-app@latest` 
2. Then I add Slice Machine with `npx @slicemachine/init@latest`
3. The init process creates a `slice-simulator.tsx` file (this already happens) **and** adds this to my JSON file:
```json
  "localSliceSimulatorURL": "http://localhost:3000/slice-simulator"
```

**Comment by comeprismic** [comment]
Hi @a-trost, this feature has been implemented. Thanks a lot for spotting it a proposing this solution. 
I'm happy to close this issue now :)
